### ISSUE TITLE
NPL section errorneouly allowing literal duplicates

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#105]
See syncids.com
ACME
008CON
NPLs 66 to 69

**Comment by yneves** [comment]
@ntgn81 This one can also benefit from the API returning a status node in response. The difference here is that it is actually creating a new document with the same `nonPatentLib` value.

**Comment by ntgn81** [comment]
Yep, I believe all of them do. Just some api would have more specific statuses than just Success/Failure
