### ISSUE TITLE
Status Indicator needs language for duplicate entered

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#106]
See syncids.com
ACME
008CON
Foreign Sections
Enter Document Number 4444444
UI correctly does not allow a duplicate entered but status bar in lower right-hand corner says Document Added.  Maybe we can have it say, "Duplicate" or the like.

**Comment by yneves** [comment]
@ntgn81 The API response for adding a document doesn't tell if it's a duplicate. I mean, the response is different it can be used, but it's not explicit. Perhaps the API can return an error if it's a duplicate? Or might be better to check client-side before sending the request. What do you think?

**Comment by ntgn81** [comment]
Yeah, I'm thinking the API might need to always return another node, `status` to specify what happened.

```json
{
   status: 'added', // 'duplicate'
   entities: {...}
}
```

**Comment by yneves** [comment]
Sounds good.

**Comment by yneves** [comment]
UI side is handled. Assigning to you for the API side.

**Comment by yneves** [comment]
This is done already. Temp code removed #137.

**Comment by ntgn81** [comment]
Great, thanks
