### ISSUE TITLE
Documents not resolving properly in medtronicsso.com database

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#113]
Browser(s): all
Login: syncids@medtronicsso.com
Password: Tikibar2
Client: SSO
Matter: Any matter (C00003035.US13)
See attached screenshot.  Should be 325 uncited references listed.

Also, when I logged out the Dashboard screen remains. To clear, I must close the browser.

![capture2](https://cloud.githubusercontent.com/assets/17907226/14530576/2b3780be-021f-11e6-803b-dd40da311acf.JPG)

**Comment by ntgn81** [comment]
@yneves , this seems to be a problem with this line here: 
https://github.com/syncids/syncids-ui/blob/develop/src/components/SimpleSuggest.js#L38

Where the input makes `new Regexp()` call fail. I think just a simple string.indexOf check should do for now.

**Comment by yneves** [comment]
Like this? #144
