### ISSUE TITLE
Low Priority: Safari cannot download IDS form or references

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#114]
Not a priority, but I was testing new UI using my iPad.  I could not download IDS form only or IDS w/ references.

**Comment by yneves** [comment]
I'm not 100% sure, maybe it changed, but it wasn't possible to download files to iOS, specially a zip. I think if it's the PDF directly, it would allow saving into book collection.

**Comment by JulieJager** [comment]
REMINDER: LOW PRIORITY at this time.  

COMMENT:  I guess the bigger question is how can our MAC users utilize SyncIDS, if at all?  Currently, they have to clone their machines to get IE to use it.  We even had a user purchase a PC just to use SyncIDS.
