### ISSUE TITLE
file button is disabled even with all required fields filled

### ISSUE THREAD

**Issue by yneves** [syncids/syncids-ui#119]

**Comment by yneves** [comment]
@ntgn81 I'm getting "internal server error" when trying to change "Filing Date" field in matters. When that happens the input field stays filled but `TodoList` still thinks the field is empty. 

My question is why the error happens even when i enter a valid date?

That's a downside of the pure render component, i should find a way of clearing the field in case of error.

**Comment by ntgn81** [comment]
I realized that the date inputs for matter/client sections are not using `DateInput` component that cleans up the date before sending it out. Can you look into that for me, please?

**Comment by yneves** [comment]
Oh that makes total sense now, i'll add it.

**Comment by ntgn81** [comment]
I updated the date handling on matter api. This can be closed, I believe. @yneves
