### ISSUE TITLE
We need users to be able to change the SyncIDS NPL serial

### ISSUE THREAD

**Issue by yneves** [syncids/syncids-ui#129]
From TODO doc:
```
We need users to be able to change the SyncIDS NPL serial# (e.g., NPL1, NPL2, etc.).
We currently use the NPL# to dedup by replacing losing NPL# with winning NPL#
 ```

**Comment by yneves** [comment]
@ntgn81 Do you have anymore info on this one? Are we turning the column into an input field?

**Comment by ntgn81** [comment]
I can see it as quite similar to foreign/us docs. Except for the NPL# column will not be visible until they specifically switch to that dedup mode.

Once it's there, they can change NPL2 => NPL3, to replace NPL2 with NPL3. Does this make sense?

**Comment by yneves** [comment]
Yeah, i think so. Will it trigger a specific API method or maybe that `rename-doc-number` would work?

**Comment by ntgn81** [comment]
The rename should work, it's not handling NPL yet, but i'll add that.

**Comment by yneves** [comment]
@ntgn81 looks like current API is working for NPL

**Comment by yneves** [comment]
I'm assigning to you, but if its really working fully for NPL, can be closed without further action.
