### ISSUE TITLE
Duplicate document status added on document add

### ISSUE THREAD

**Issue by ntgn81** [syncids/syncids-ui#135]
I added status="duplicate" in json response, next to entities, this works for all document types.

https://syncids-api.herokuapp.com/api/documents/add-to-matter?firmName=syncidscom&q=syncids.com&showAll=false&loginEmail=nam@syncids.com&matterId=22394&documentNumber=4444444&type=US

https://syncids-api.herokuapp.com/api/documents/add-to-matter?firmName=syncidscom&q=syncids.com&showAll=false&loginEmail=nam@syncids.com&matterId=22394&documentNumber=npl+description&type=Other

Let me know if it works for you. We can remove your temporary code of dup checking.

**Comment by yneves** [comment]
Fixed here #137.
