### ISSUE TITLE
Default Filer Information is not flowing to new matter

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#136]
Default Filer info in Client Section should always flow to the Matter section

1. Create new client
2. Enter Default Filer information
3. Create new matter
RESULT:  Default Filer information **should** automatically flow to Filer information in Matter section but it is not.  

This is how it is done now.  The idea is to be able to change the Filer information on a matter-by-matter basis, if needed.  This information should not be blank because when the IDS transmittal generates, its the Filer information in the matter section that it pulls from.

**Comment by ntgn81** [comment]
@JulieJager, we'll have this fixed by tomorrow after code review

**Comment by yneves** [comment]
Merged.
