### ISSUE TITLE
Large Matters

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#152]
For Large Matters, it can take some time for the table to build after clicking on the matter in the dashboard.  While the table is building can our users see some sort of "Please Wait while we build..." notification?  Sometime that indicates its working?  Thank you!  

Also, I am unable to generate the IDS Form Only or the IDS with references from this database.

**Comment by ntgn81** [comment]
@yneves, I wonder if we could hook into react's before and after render to show some kind of notification for super large tables?

**Comment by yneves** [comment]
Yeah, definitely.

**Comment by yneves** [comment]
Fixed!
