### ISSUE TITLE
EFS-Web IDS Form:  Application # and Filing Date

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#154]
1.  We need to strip out any / or , from the Application # before entering into the EFS-Web IDS Form.  The form only allows for 8 digits.
    NOTE:  EFS-Web will allow the IDS form to be submitted even if a real Application # is not listed.  For example, "Pending" or "TBD" or no data is shown the USPTO will still accept.  Good news!

2.  We should convert the Filing Date to YYYY/MM/DD format before entering into the EFS-Web IDS Form.  Or we can make users enter it that way in the UI.  Whichever is easier.

THANKS!

**Comment by ntgn81** [comment]
@JulieJager , what about letters, and longer application numbers? Like `WO2010US44136` ?

**Comment by JulieJager** [comment]
Letters flow to Application # section of the IDS form (Top right).  There is a limit of 8 characters (letters or numbers).  

FYI:  This IDS form is used for US applications only.  If WO2010US44136 is the Application # in the Matter Section, that is fine.  Users will never generate an IDS form for this foreign country matter.

**Comment by ntgn81** [comment]
This is done, @JulieJager.

**Comment by ntgn81** [comment]
As for the date, looks like EFS Web form is expecting YYYY-MM-DD, I updated the code also

**Comment by ntgn81** [comment]
@JulieJager , could you please retest and close this?

**Comment by JulieJager** [comment]
Looks good!  Thank you
