### ISSUE TITLE
Cannot Add a New NPL description

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#155]
I just get the "Adding New Document(s)..." flag.  Nothing happens.

**Comment by ntgn81** [comment]
Fixed now, thanks for the catch!

**Comment by JulieJager** [comment]
I think sometime is broke.  When I type in a new description in the NPL section, I get NPL#s and looks like US reference #s.  Just type anything in an NPL section and you will see what i mean.

**Comment by ntgn81** [comment]
Hmm, which user are you using? I'm on nam@syncids.com and I can't see the issue

**Comment by JulieJager** [comment]
lawyer@lawfirm.com
10000
4

I typed in "New Description" but got back "NPL1,NPL2,NPL3" and the second time I got "6000002,6000001,600000"

**Comment by ntgn81** [comment]
@JulieJager , can you please try again? The issue was with things being out of sync.

The old logic was looking at `nextOtherDocNumber` in `clientsdb` to decide what the next available NPL number is, and it wasn't in sync with the actual available number. I changed the logic to be more robust.

**Comment by JulieJager** [comment]
Looks good.  Seems to work now.  Thank you!
