### ISSUE TITLE
When Renaming Matters, the name does not update in two-way sync box

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#161]
Example: 
Client: 10000
Matter: 10000US1
Matter: 10000US2

Original names in this family were 1 and 2.  Two-way Sync Matter box still shows 1,2.

**Comment by yneves** [comment]
@ntgn81 This seems to come straight from API in `twoWayRelatedMatters` field.

**Comment by ntgn81** [comment]
@JulieJager , fixed

**Comment by JulieJager** [comment]
@ntgn81 I just experienced this issue again.  See image below.  
syncids.com
Acme-007
I changed 007 to P0123456(CLIENTNUMBER), then changed it a few more times before going back to 007.  Two-Way sync still shows it as P0123456(CLIENTNUMBER).
![capture](https://cloud.githubusercontent.com/assets/17907226/15587450/e0f4c88a-234e-11e6-9852-96f3a2f42ab3.JPG)
