### ISSUE TITLE
To Do List needs to backwards auto-update

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#162]
Example:  
Filter set to Acme (To Do List); "Show All" not checked
Matter 1: 10 cited
Matter 2: 10 uncited
To Do List correctly shows Matter 2 only
When I manually unchecked 4 references in Matter 1, my To Do List is not automatically updating to include Matter 1

Same idea when you Close a Matter.  It should automatically be removed from the To Do List if in view.

**Comment by yneves** [comment]
@ntgn81 This one also looking that needs to be handled server side. I see `showAll` param is sent in every request, i assume new entities collection should be returned?

**Comment by ntgn81** [comment]
Yep, this is api bug. Fixed - @JulieJager
