### ISSUE TITLE
LOW PRIORITY:  Two-Way Sync Box - When self matter remains

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#164]
Matters 1, 2, 3 are two-way synced
While in Matter 3, Remove from syncing
While in Matter 2, Remove from syncing
RESULT:  While in Matter 1, user will still see Matter 1 is synced with itself.
I think we need to write it so if a Matter is solely synced with itself, we automatically clear it.

**Comment by ntgn81** [comment]
@JulieJager , this is weird, I'm not able to reproduce it

**Comment by JulieJager** [comment]
I could not recreate either.  Maybe it only affects matters synced before a certain feature was implemented.  Maybe you could search SQL for any Two-way instructions with only one matter?
