### ISSUE TITLE
NPL Auto-Suggest pulling from Matter

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#171]
We need to confirm that when a user begins to type in the NPL section, the auto-suggest boxes are pulling all NPL descriptions for that Client.  Jim was not 100% sure if it was.  We might need a slick way to design this (show 3 at a time or something like).

Also, can we have the suggestion box(s) appear above the cell rather than below?  Thank you!

**Comment by yneves** [comment]
This is all handled now. @JulieJager  I made an attempt to improve NPL suggestions look without adding a border as delimiter (looks awful), let me know if its good enough or i should go with the border anyway. It also might need some tweaking in API as mentioned in the PR @ntgn81

**Comment by yneves** [comment]
![image](https://cloud.githubusercontent.com/assets/5215669/15691456/4af98d1a-275f-11e6-9791-fc571e48d218.png)
