### ISSUE TITLE
Status Tag 

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#172]
1.  We keep missing the Status Tag after entering a document, entering a dup., etc.  The Status Tag seems to be at the bottom right in some cases, and the top right in others.  It doesn't matter to us where it is located on the right side, as long as it's consistent.  Maybe we experienced this from browser to browser?  Also, please change the background color to something more noticeable.
2.  Remove the leading zero for foreign #s when mentioned in a Status Tag.

THANK YOU!!

**Comment by yneves** [comment]
Fixed #180
