### ISSUE TITLE
UI is not auto-converting document number with commas

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#178]
Patent Nos. typically have commas in them.  Some users may enter 8,000,000.  Our UI needs to remove the commas AND resolve it as 8000000.  Currently, Status Tag says its added but it is not shown.

**Comment by ntgn81** [comment]
@JulieJager , this is weird. It's working for me, could you please try again?

**Comment by JulieJager** [comment]
I tried again still not working.  I entered a document number such as 5,545,555, tabbed out.  Screen flips view to top of page, Status Tag says Document 5,545,555 was added, but it is not there.

**Comment by yneves** [comment]
Happens just for US documents. I'm removing commas before sending to server for all types now.

**Comment by yneves** [comment]
Fixed #204
