### ISSUE TITLE
LOW PRIORITY: Add Delete from Family 

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#187]
In the Document Section, please add to the gear box a Delete from Family options.

Thanks, as always!

**Comment by ntgn81** [comment]
Would this only delete from two-way-synced family? Or also delete it from matters that are one-way-synced from the current matter?

**Comment by JulieJager** [comment]
I think this "rat hole" may get long.  It would include any one-way and any two-way the one-way matter is in, and so on.  Wherever the bad reference flowed due to syncing instructions at that time needs to be deleted. I am moving this to LOW PRIORITY since our clients do not currently enjoy this feature.

**Comment by yneves** [comment]
UI done here #421

**Comment by yneves** [comment]
Done
