### ISSUE TITLE
Date and e-signature on IDS Form

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#188]
I know this form is work in progress.  Just documenting my finds below: 

1. Today's date needs to resolve on the last page YYYY-MM-DD

2.  A Default Filer's checkmark for e-signature at the Client level should automatically flow wherever that filer is mentioned in the Matter section (presently mentioned and going forward).

However, if a Filer checks the e-signature box at the Matter level that checkmark should NOT flow to wherever else the filer's name is mentioned in the database.

It is only at the Client level that it should flow everywhere automatically.
![e-signature checkmark to follow whereever filer is mentioned in database]
(https://cloud.githubusercontent.com/assets/17907226/15303120/d159583a-1b7b-11e6-9230-c6d79d8500dd.JPG)

**Comment by ntgn81** [comment]
We might need to rethink this, as right now e-signature is attached to filer by email, and that is shared across clients/matters.

**Comment by JulieJager** [comment]
Okay.  If email has a checkbox in SQL, having it show up everywhere at this point is perfectly fine.  Thanks

**Comment by ntgn81** [comment]
Keeping this issue open for tracking

**Comment by JulieJager** [comment]
FRIENDLY REMINDER:  Today's date needs to resolve on the last page YYYY-MM-DD (always) regardless if e-signature is present.  Currently, it is only resolving when an e-signature is added.

**Comment by ntgn81** [comment]
Done, @JulieJager
