### ISSUE TITLE
Update Client/BU ID box to allow: (ClientName)

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#191]
Currently, in the client section, users are able to enter in parenthesis the real name of their clients.  Any data within the ()s should not flow to the IDS form but should be seen in the UI.  We do this already.  See ClientName column.  

Example in sheppardmullin.com database:

![46fj with real client name in parens](https://cloud.githubusercontent.com/assets/17907226/15310150/fb7fe6d8-1bb2-11e6-92fb-474b4b730c54.JPG)

![ids form showing how real client names does not resolve](https://cloud.githubusercontent.com/assets/17907226/15310151/fb7ff1d2-1bb2-11e6-894c-ffd5a8f588b5.JPG)

**Comment by ntgn81** [comment]
@yneves , can you please take a look into this? I think this is just UI, putting clientNumber and clientName in the same textbox on render, and on change, split it out into 2 fields on the way out

**Comment by yneves** [comment]
@ntgn81 Yeah i'm looking. It's 99% client side, still need API to include `clientName` field in `clientList` in response.

**Comment by ntgn81** [comment]
Yep, I'll add clientName next to clientNumber
