### ISSUE TITLE
One-Way from Matters & Prior Art Categories

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#199]
One-Way Import from Matters
1.  Do not allow a user to enter in a matter that does not exist.  A pop-up indicating this would be great.
2.  Add a grayed-out example in the box:  (e.g., 001,002,003) simply to show users they can add more than one matter separated by a comma.
3.  When a category is deleted or changed in the Client section, the "Sync with Categories" header in the Matter section needs to be updated as well.  
![pacate](https://cloud.githubusercontent.com/assets/17907226/15360757/83a57bb4-1cd4-11e6-80fd-385978d131ad.JPG)

Prior Art Categories
1.  Add a grayed-out example in the box:  (e.g., pens,pencils,markers).

If you think these examples would be better shown in a different way, please do so.

**Comment by yneves** [comment]
This is now fully handled after #214
