### ISSUE TITLE
To Do List Excel Report

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#202]
To Do Report is capturing incorrect Client/Matter Numbers but all other data seems fine (e.g., cited/uncited #s, Timing, Statement, etc):
Browser: Edge
Login: lawyer@lawfirm.com; Tikibar1 
Filter set to lawfirm.com
To Do List via UI:
![screen1](https://cloud.githubusercontent.com/assets/17907226/15370137/1839381c-1cfb-11e6-8439-d0e999147a10.JPG)
What was exported to To Do List excel:
![screen2](https://cloud.githubusercontent.com/assets/17907226/15370144/2079e13e-1cfb-11e6-8775-9c5339b288dd.JPG)

**Comment by ntgn81** [comment]
Thanks for the catch. This was showing the id, not numbers. I updated the order to be the same as on the UI too. @JulieJager

**Comment by JulieJager** [comment]
Thanks, as always!!
