### ISSUE TITLE
Create default focus on "Confirm" or "Cancel"

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#217]
@yneves Similar to what you did in the Client/BU section, please grant users the ability to hit "Enter" in the following places:

Login Screen: focus on "Login"
Dashboard:  File Button, focus on "Confirm"
Matter Section:  Remove Two-Way Related Matter, focus on "Cancel" 
Matter section:  Create a new Matter, focus on "Confirm"
Matter section:  Rename a Matter, focus on "Confirm"

Thank you!!

**Comment by yneves** [comment]
This is done here #221. Only difference is that in login and rename modals the focus goes to the input field, but hitting enter still confirms the operation.
