### ISSUE TITLE
Cross Firm Access?

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#218]
@ntgn81  I was still logged into @fitcheven.com when I opened the new UI today (Firefox).  I logged out and back in with @pillsburylaw.com and started testing the two-way syncing when I realized I was still in the @fitcheven matter that was initially shown.  I then logged into the @fitcheven.com database to see if the change I made actually took, it did. 

See the login information against the Default Filer information in the image below:

<img width="960" alt="crossfirms" src="https://cloud.githubusercontent.com/assets/17907226/15506816/9ca06c0a-218e-11e6-84e9-f489895d3c82.png">

**Comment by ntgn81** [comment]
Yep, we'll get it fixed. @yneves , this is just a matter of clearing everything in store when user logs out. I can get to it later if you can't.

**Comment by yneves** [comment]
Don't worry, i got it.

**Comment by ntgn81** [comment]
💯

**Comment by yneves** [comment]
Fixed here #220
