### ISSUE TITLE
Documents Section: Sorting

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#219]
@ntgn81 Sorting Document Numbers does not seem to work correctly when the view is ALL.  Seems to work just fine if Cited or Uncited is view.

**Comment by ntgn81** [comment]
@JulieJager , can you please give me more details on how it doesn't work?

**Comment by JulieJager** [comment]
@ntgn81 Sure.  @fitcheven.com; client 1410; matter 102286.  After clicking sort the foreign section did not sort by document number correctly.  At first, I thought it was sorting by Document Number and Country Code (image below kind of shows that), but then I saw in a different matter country code didn't seem to affect sorting. 
![capture](https://cloud.githubusercontent.com/assets/17907226/15508741/49cec168-2196-11e6-9984-4759327a69c1.JPG)

**Comment by JulieJager** [comment]
Here is one in the US Section:  FitchEven.com; 7115-130309-US

![capture2](https://cloud.githubusercontent.com/assets/17907226/15509031/91f45ac4-2197-11e6-85a8-746a9dadf87a.JPG)

**Comment by ntgn81** [comment]
That is great, I'll get it fixed today. Thanks!

**Comment by ntgn81** [comment]
This was a bit tricky, the documents with kind code messed it up a bit for me.

As for '0123' vs '100', we are considering '0123' as '123', that's why it would go after 100, how else would you like it to be sorted?

**Comment by JulieJager** [comment]
For documents that start with zero, know these are the last two digits of a year (e.g., 01022333 is actually **20**0122333) so we need to consider the leading 0.  That is, 0123 should be listed before 100.

On another note, I had a training session today with a real client who uses our current UI and she asked if we could sort by country code first then document number.  I think the answer is no but I wanted to ask you first.  Let me know at your convenience.

**Comment by ntgn81** [comment]
@JulieJager , with that logic 0123 would be `200123`, which goes after 100 then, since 200123 > 100 ?

Also, sorting by country code first should be easy. Do you want it to be the default (with updates to the text on UI?) or as another option?

**Comment by JulieJager** [comment]
@ntgn81 Sorry for the confusion.  I was trying to explain why we need to consider the leading 0 during sorting.

If user enters 0123, it should go before 100
If user enters 200123, it should go after 100

That's great new about the CC!  Order of enter should be default; if user clicks sort, we should sort by country code then document number.  Down the road, maybe we can offer options: "Sort by Doc No. only" and "Sort by CC then Doc No."

**Comment by ntgn81** [comment]
Okay I'm still confused, haha. Unless I missed something, I can't understand why 0123 goes before 100.

200123 goes after because 200123, as a number, is larger than 100, right?

**Comment by JulieJager** [comment]
After clicking sort in the current UI, this is what I get:

![capture](https://cloud.githubusercontent.com/assets/17907226/15547573/fa78373c-2269-11e6-8d84-1c69056dd94e.JPG)

0123 is less than 100.

**Comment by JulieJager** [comment]
Let add this topic to our call tomorrow night.  I'm confused too! :)
