### ISSUE TITLE
Question re Reset Password Title

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#226]
If I am a user and cannot remember my password, how do I recover it?  

I think the word "reset" suggests change which is already offered in the UI.  Maybe this should say "Forget Password".  I think the action will be an email from us sharing their current password, correct?

**Comment by yneves** [comment]
@JulieJager Yes, expect that you get a new password by email instead of the current.

**Comment by yneves** [comment]
Fixed here #

**Comment by JulieJager** [comment]
Could you type "Forgot Password"  I misspelled that above.  My apologizes.

**Comment by JulieJager** [comment]
@yneves Please return to "Reset Password"  Thank you.
