### ISSUE TITLE
Statement section needs updating in Dashboard Section

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#227]
Add to Timing 1.97(c) NONE which will generate a PTO fee (amount depends on entity size)
Remove from Timing 1.97(d) the NONE option.

See Acme-007
Also, when choosing Timing 1.97(c), I sometimes get in the Statement column a small icon with what looks like 2 small arrows.  Please do not allow this.

![capture](https://cloud.githubusercontent.com/assets/17907226/15586650/215ce21c-234b-11e6-8795-509ae3729457.JPG)
  See image:  

Thank you, as always!

**Comment by yneves** [comment]
Fixed.
