### ISSUE TITLE
LOW PRIORITY: Closed matters remains in To Do List & Excel Report for One Matter

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#246]
@ntgn81 Filter set to Client|Matter which shows a To Do List for a family (open matters with at least 1 uncited reference)
I closed one of those matters and it still remained in To Do List

![capture](https://cloud.githubusercontent.com/assets/17907226/15748369/3e018702-28a4-11e6-8959-51bd2028710e.JPG)

Also, I should be able to set my filter to Client|Matter|One to generate an excel for one matter only.  I do not believe you were aware of this filtering previously.

**Comment by yneves** [comment]
Fixed here #264

**Comment by ntgn81** [comment]
@JulieJager , yeah, I don't know of that combination. Which matter would it generate excel for? The first one?

**Comment by JulieJager** [comment]
@ntgn81 It would generate the MatterNumber mentioned in the filter.  For example: Acme|007|One would show just Matter 007 information.

**Comment by JulieJager** [comment]
@ntgn81 It properly filters to the one matter in the UI (Yay!), but I cannot download the excel report.  Actually, downloading the Excel Report doesn't seem to be working for any filter options...neither does the "Download the To Do List to Excel."
