### ISSUE TITLE
Add ability to continue to two-way sync

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#247]
Matter A and B are two-way synced
Matter C and D are two-way synced

Currently, if I want to marry these two families together I cannot since none of the matters have a two-way syncing box available for input.  We need a constant ability to add a matter to a group.

I can't believe we didn't think of this sooner! :)

**Comment by ntgn81** [comment]
Hmm, okay. Let's think about it for a bit before merging. This is good stuff though!

**Comment by yneves** [comment]
Client side done here #259, assigning to you for server side.

**Comment by JulieJager** [comment]
Just checking on the status.  Can we merge this soon?

**Comment by ntgn81** [comment]
@JulieJager , yep, I'm working on this.
