### ISSUE TITLE
De-Duplicating: Do not allow renaming to non-existing NPL#

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#248]
@yneves Please make NPL # box a little larger - enough to store NPL####.  Space can be taken from the Notes section, if necessary.  Also, please do not allow users to rename an NPL to a non-existing NPL.  For example, I was able to rename NPL10 to NPL10000.  This will cause problems down the road since we (SyncIDS) is the one who assigns NPL#s.

Thank you!

**Comment by yneves** [comment]
Fixed here #251
