### ISSUE TITLE
Cannot manually check cited or T boxes

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#262]
I cannot check the cited box or translation box.  I tested over all the browsers. 

This may be related to #261

**Comment by yneves** [comment]
It's working for me locally, tested on Chrome/Mac and Edge/Win. Any more information you can give me @JulieJager?

**Comment by JulieJager** [comment]
Thanks for looking into this @yneves .  I think it only happens after #261 .

**Comment by ntgn81** [comment]
@JulieJager , great catch Julie! You can actually start coding soon at this rate.

@yneves, the `(newValue)` check ignores `false` which is what happened in this case

**Comment by yneves** [comment]
Indeed. Fixed here #266
