### ISSUE TITLE
Home2

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#282]
@ntgn81 Will Home2's functionalities be up soon?  I have two migrations to upload (~15 text files of various data to upload).  I initially thought "no rush" but I get the feeling this may take longer than I expected.  Home2 as you many know, stores software that helps up migrate data and CLEAN messy data.  Is this something Jim should tackle?

**Comment by ntgn81** [comment]
@JulieJager, I'll work on that first thing tonight!

**Comment by JulieJager** [comment]
Nam:  I just spoke with Jim.  At this time, please return Home2 to original state.  We do not need to move Home2 to the new UI at this time.  Is this doable?

**Comment by ntgn81** [comment]
Hmm I don't think we can do that. Do you mean to make home2 point to old database? Then it'd be disconnected from everything else.

**Comment by JulieJager** [comment]
No.  We need Home2 to point to new database.  
Jim can explain to you tomorrow night on how Home2 is used ... why it needs to point to the new database.
