### ISSUE TITLE
VERY LOW PRIORITY: FAQ correction

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#283]
Where are my IDS forms and prior art PDFs?
change the word "cited" to "uncited" 

The to-do list includes a folder for each matter. Inside that folder is everything you need to file that IDS including a completed IDS form, **cited** foreign PDFs, and **cited** non-patent literature PDFs. If anything changes anywhere in the database that affects that matter, the folder is automatically updated. 

Does SyncIDS monitor Public PAIR activity for Office Actions?  Remove "At no cost to you,"

Yes. SyncIDS will sweep weekly for Office Actions and Notices of Allowance. A $20 fee is charged only when SyncIDS finds and enters a document into a matter. Since the document automatically flows to other synced matters, IDSs will likely need to be filed (standard IDS fees apply). Service must be requested. 

APPLICATION OVERVIEW
Add the following language under the first sentence:

SyncIDS is a prior art database. When new documents or matters are added to the database, SyncIDS automatically shows all of the IDSs that need to be filed, and everything needed to file each IDS is automatically placed in a separate folder including a completed IDS form and any non-U.S. PDFs.

SyncIDS is divided in to four sections. (1) The Dashboard automatically generates IDSs that need to be filed. (2) The Client/BU ID allows you to view and modify information for each client or business unit, such as the default filer and prior art categories for that client. (3) The Matter ID allows you to view and modify information for each matter, such as the first inventor’s name and any links to any related matters. (4) The Documents include all of the prior art for a matter.

**Comment by yneves** [comment]
Fixed here #285
