### ISSUE TITLE
*EFS-Web IDS form - Cite Numbering Issue in both Production and Development

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#308]
Citing numbering seems to start with last number of the section.  

![capture](https://cloud.githubusercontent.com/assets/17907226/16323720/8fc733c8-3972-11e6-933a-a63f9df02370.JPG)

**Comment by ntgn81** [comment]
@JulieJager , can you give me matter number you tried this on, please? I'm not able to reproduce it

**Comment by JulieJager** [comment]
Sure.  In syncids.com database, client 45-MP; matter A-214066

**Comment by ntgn81** [comment]
Hmm I"m not able to get incorrect numbering, can you try again? This is the link:

https://syncids-api-prod.herokuapp.com/api/ids/22177/filing-package

**Comment by ntgn81** [comment]
Cited checkbox, updating client/matter should work on dev now.

**Comment by JulieJager** [comment]
Ugh.  I just releized why this happens.  I use PDF Nuance, not Adobe.  I switched to Adobe and it works fine.  So sorry but happy we're closing this issue. :)

**Comment by ntgn81** [comment]
Yay
