### ISSUE TITLE
Brochure Page

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#322]
@yneves Can you somehow recreate the look of our current brochure page.  I have several pics given to us by the creator of our home page.  

Currently, in the new UI, it seems Overview is our brochure page.  Can we create a home page at the SyncIDS logo?  Overview is not our current home page.  

I am not sure what either of your thoughts are.  We could point the new UI to our current brochure page as well.

**Comment by yneves** [comment]
@JulieJager I can recreate it on new website, not a problem. Would you send me those pictures to use pls?

**Comment by yneves** [comment]
Done here #339

**Comment by JulieJager** [comment]
I didn't see your message to me a few days ago, I'm sorry.  Yes.  I can send those to you.
