### ISSUE TITLE
URGENT:  Cannot Click T or cited box

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#323]
Hello-

This issue has happened here and there.  I cannot manually check the cited box or the translation (T) box.

**Comment by yneves** [comment]
@JulieJager Are you on production or development? I just pushed a big update to development site, can you try there pls?

**Comment by yneves** [comment]
@JulieJager There was really an issue in Internet Explorer. It's fixed, should be in production soon. #325

**Comment by JulieJager** [comment]
@ntgn81 Ok.  However, I just tested in firefox and it did not work there either.  may still be related though.

**Comment by yneves** [comment]
@JulieJager You're right, i confirmed firefox has the same issue as IE, and the fix is good for it too.

**Comment by JulieJager** [comment]
Awesome! Thanks.
