### ISSUE TITLE
LOW LOW PRIORITY: Tighten up cells in Client/Matter sections to show relationship

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#328]
For example,

Remove the black real estate between title of section and cells if related.  Also, the black between the cells can be reduced as well.  Thank you

![capture](https://cloud.githubusercontent.com/assets/17907226/16456273/0666c34a-3ddd-11e6-8ede-3ea24927e67c.JPG)

![capture3](https://cloud.githubusercontent.com/assets/17907226/16456369/44c98ca8-3ddd-11e6-92d2-1d6612547516.JPG)

**Comment by yneves** [comment]
Done here #353
