### ISSUE TITLE
LOW LOW PRIORITY:  Client Section: Change "Large" Entity Size to "Undiscounted"

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#329]
@yneves  Change "Large" to "Undiscounted"

Change size of box to accommodate larger word.  FYI:  Billing period box can be reduced if necessary as largest word is "Immediately".  
![capture3](https://cloud.githubusercontent.com/assets/17907226/16456496/a2de54c2-3ddd-11e6-958a-301fb790c5d1.JPG)

**Comment by yneves** [comment]
Fixed here #332
