### ISSUE TITLE
URGENT: Quotes (") not translating in NPL section

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#330]
â€œImidazolium salts and their polymeric materials for biological applicationsâ€

See pabstpatent.com
Client: ARSIA

**Comment by yneves** [comment]
@JulieJager Was this one entered in new UI or old UI?

@ntgn81 How can i log in the prod db and see these?

**Comment by JulieJager** [comment]
@yneves These were entered in old UI.

Login:
http://new.syncids.com/#/?_k=icuv77 
User: syncids@pabstpatent.com
Password: Tikibar2

Just be careful not to change any data.  This is our customer's real database but it will show you what I see.

**Comment by yneves** [comment]
@JulieJager This is public. I deleted the password from your comment. I'll be careful :-)

**Comment by JulieJager** [comment]
Thank you!

**Comment by yneves** [comment]
@ntgn81 I think we have a charset problem here. I checked this entry in the old UI:

```BAKER, et al., “Fluorescence quenching immunoassay performed in an ionic liquid”, Royal Doc Chem., (27):2851-3 (2006).```

The quote character seems to be using Cyrillic (KOI8-U), but the new API is encoding with UTF-8. I guess old API is storing with different charset than new API.

**Comment by JulieJager** [comment]
This is more than quotes it now seems.  Also, FYI:  I do not see this problem everywhere, so far just pabstpatentcom NPLs.  
![capture3](https://cloud.githubusercontent.com/assets/17907226/16510489/23e039ee-3f0c-11e6-8128-785e76927bbe.JPG)

**Comment by JulieJager** [comment]
FYI:  Our client just reported this issue (I reported the finding earlier).  This is now a URGENT task. Thanks!

**Comment by ntgn81** [comment]
@JulieJager , fixed now. Please give it a try when you get a chance.

**Comment by ntgn81** [comment]
@JulieJager , is it still broken?

**Comment by JulieJager** [comment]
Sorry, having a hard time attached an image.  It is 98%.  
![capture4](https://cloud.githubusercontent.com/assets/17907226/16530780/4b7b2274-3f8f-11e6-93df-a6fcc24ac71a.JPG)

**Comment by ntgn81** [comment]
Hmm this seems to be a bigger problem with those special symbols. I'll need more time to look into this.

**Comment by JulieJager** [comment]
@ntgn81 Can we take a look at this soon?  Thanks!

**Comment by ntgn81** [comment]
@JulieJager , fixed now. Sorry it took so long.

**Comment by JulieJager** [comment]
@ntgn81 Thanks.  I assume this is another code that needs translating?  Old UI shows these as "

![capture](https://cloud.githubusercontent.com/assets/17907226/18131345/0e668cae-6f58-11e6-9d28-7be96395fc1f.JPG)

**Comment by ntgn81** [comment]
Nopes, the new UI was missing the mapping for `$qq#`. Can you try again in a few minutes, please?

**Comment by JulieJager** [comment]
@ntgn81 Looks good now!  Thank you!
