### ISSUE TITLE
LOW LOW PRIORITY:  $ in Invoice

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#334]
After a user tell SyncIDS they filed an IDS, a SyncIDS invoice is generated and sent to that user.  The PDF of the invoices includes a dollar sign as shown below.  This is fine for now, just wanted to get this down.  NO RUSH to fix.  

![capture3](https://cloud.githubusercontent.com/assets/17907226/16489822/c25f1dd0-3e9c-11e6-8243-21fb47c9334c.JPG)

**Comment by ntgn81** [comment]
@JulieJager , fixed
