### ISSUE TITLE
URGENT:  Character Code missing from SQL \ Creating issue?

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#335]
I cannot access UA-UA14-18 via the new UI or old UI.  The user entered new NPL references.  I noticed the NPL descriptions do not include the space character codes like they used to.  See screen shot below.  Could these be what is blocking access to the matter?

![capture3](https://cloud.githubusercontent.com/assets/17907226/16490253/72ee861c-3e9e-11e6-82bf-af11e199dc66.JPG)

Email from client:
Julie,
I was adding references to UA-UA14-018

DRAGER, “Drager PSS® BG 4 closed-circuit breathing apparatus”, http://www.draeger.com/sites/enus_us/Pages/Fire-Services/Draeger-PSS-BG-4-plus.aspx,  .
5 pages downloaded from the internet 09/25/2013.

This references was entered twice. When I deleted one of  the references the blank entry was still there. The only way to clear it was to mark as cited. Now the dashboard is showing 1 cited and 23 uncited. How do I make a references go away that has been uploaded?

**Comment by JulieJager** [comment]
additionally, I cannot generate an IDS with the references.

**Comment by ntgn81** [comment]
I can look into it in a bit. @yneves , can you give it a try, please? Do you see any api errors?

**Comment by yneves** [comment]
In dev this string works normally. But i can see it has the same chars i mentioned here #330.
