### ISSUE TITLE
Cannot make changes or download IDS w/ references

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#337]
Production

I cannot make changes in the UA client (pabstpatentcom database).  User added NPL descriptions and documents to matter UA14-018 ironically.  Now I cannot create a new Matter for UA either.

**Comment by ntgn81** [comment]
@JulieJager , can you provide more details on this please? I'm able to download ids with references, and make changes.

**Comment by JulieJager** [comment]
This issue was a result of ZIP file. It downloading last week. We can close.
