### ISSUE TITLE
URGENT:  Cannot download IDS forms or references for finchmaloney

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#338]
of which I am launch to at 1 pm Ct

![capture3](https://cloud.githubusercontent.com/assets/17907226/16497551/26efbe60-3ebd-11e6-8d9f-0b561a154fe2.JPG)

**Comment by ntgn81** [comment]
Oh yeah, dev has some issues with downloading things. That feature should work fine on production.

**Comment by JulieJager** [comment]
Thanks for your quick response.  I am having trouble downloading in PROD, unfortunately.  I am still having intermittent access problems as well.

**Comment by JulieJager** [comment]
FYI:  I cannot log into any database at this time.
