### ISSUE TITLE
URGENT:  Cannot click "File" Button

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#346]
All the file buttons are grey, even if all required field are fulfilled.

**Comment by JulieJager** [comment]
Actually, DEV looks good.  File button works there.  I will be doing the demo here.  Please do not push anything in between 9-10 am ET.  Thanks!!

**Comment by yneves** [comment]
Fixed here #344.

**Comment by JulieJager** [comment]
In Production site, the File button is still grey.  I cannot click it even if all required fields are met.

**Comment by ntgn81** [comment]
@JulieJager , pushed new change to production, should be able to file now.

@yneves , for some reason, I can only file once. Clicking file the second time does not show the modal window.
