### ISSUE TITLE
URGENT: Leading 0 in Foreign Section is showing

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#347]
Per beta tester (pabstpatent)
![capture3](https://cloud.githubusercontent.com/assets/17907226/16526733/3a09b94a-3f78-11e6-890c-63451cd4e2f6.JPG)
 email, leading zero is showing in the UI in the foreign section.

**Comment by ntgn81** [comment]
@yneves , looks like an UI thing. Can you check? I don't think anything changed on the server.

**Comment by yneves** [comment]
Fixed here #348. Sorry, my mistake during the doc list refactoring.
