### ISSUE TITLE
Monthly Invoices did not generate

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#354]
Usually the 1st day of the month, monthly invoices are generated and sent to accounting@syncids.com for review. This did not happen this month. If we could solve this in the next few days that would be great. That is, I'm on vacation so I'm in no rush to work. ;) Just wanted to document this.

**Comment by ntgn81** [comment]
Thanks for the report, I'll look into it!

**Comment by ntgn81** [comment]
@JulieJager , weird, I was able to get all those invoices after changing the recipient to my email just now by hitting syncids.com/monthly.asp directly

![image](https://cloud.githubusercontent.com/assets/4622542/16606053/ada355d6-4302-11e6-80b0-8e4e1bc21a03.png)

**Comment by ntgn81** [comment]
@JulieJager , looks like the monthly script was not waiting. Something must have changed, I chagned the script to wait 10 seconds. Seems to be working now.

Let me know when you want it to be ran, or just run http://syncids.com/monthly.asp whenever you want :)

**Comment by JulieJager** [comment]
Thanks, @ntgn81 

Starting next month, please auto set according to instructions below.  There is a reason the excel version of pillsburylaw.com's PDF needs to generate before the PDFs.  Has to do with legacy count, I believe. 

1.	Pillsburylaw.com's excel month invoice is auto-generated at 7:30 am and emailed to accounting@syncids.com  (this actually may still be set to send to me). 
2.	PDF is auto-generated at 8:00 am and emailed to accounting@syncids.com 
3.	Review and confirm excel total matches PDF
4.	Review and confirm excel Invoice Number matches PDF

Currently, Pillsburylaw is only firm that has requested they receive a duplicate excel invoice

SyncIDS Users can generate this invoice anytime by updating the URL below with the necessary firm and user information: 

http://syncids.com/api/billing/ExcelInvoice.asp?User=DOCKET_IP@PILLSBURYLAW.COM
