### ISSUE TITLE
REPORT:  Matter Section not opening

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#362]
I cannot recreate this problem. - Julie

From: Robert Plotkin [mailto:rplotkin@rplotkin.com] 
Sent: Wednesday, July 6, 2016 8:45 AM
To: Julie SyncIDS <julie@syncids.com>
Cc: Kim Hauser (Kim.Hauser@clairvolex.com) <Kim.Hauser@clairvolex.com>
Subject: Problem with SyncIDS 4.0

Hi Julie,

Just thought you should know that the matter information is no longer showing up for me in SyncIDS 4.0 when I click on the pointer at the far right of the “Matter ID” bar:

 
![capture jpg](https://cloud.githubusercontent.com/assets/17907226/16620458/1d21873e-4358-11e6-8735-5eb63955feda.png)

This was working a few days ago, but now in all matters when I click on that pointer, it rotates downward but no matter information appears.  I have to go into the old version of SyncIDS in order to view and edit the matter information.

Robert @ Rplotkin.com

**Comment by ntgn81** [comment]
I can't either, can you please check with them again to see if they still have issues with it?

**Comment by ntgn81** [comment]
Oh, and also, what browser they are using?

**Comment by JulieJager** [comment]
Thanks.  I will report back with his response as soon as I receive. :)

**Comment by JulieJager** [comment]
Customer reports all is working well now.  He was using FireFox.  Thanks, Nam.  BTW, he complimented us on the NEW button other features!  Great Great Job!
