### ISSUE TITLE
Matter Closed in Old UI but box is not checked in New UI

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#368]
syncids@rplotkin.com
M0002
1053
Matter is closed in old UI, acts likes its closed in new UI, but the Matter Closed box is not checked in new UI.  Is the checkmark white against a white background?  I thought I saw on an unrelated screenshot where the Matter Closed box had a green background.  FYI:  I do not want to check this specific matter's Matter Closed box as the references will flow if I uncheck it.

I tested both PRO & DEV

![capture4](https://cloud.githubusercontent.com/assets/17907226/16643183/d2ab0c9a-43d7-11e6-804c-8b48f5e0db41.JPG)

**Comment by ntgn81** [comment]
@yneves , the api returns matterClosed: 'ON', but UI is not checking the box, can you take a look for me? Thanks!

http://syncids-api-prod.herokuapp.com/api/matters/23542

**Comment by yneves** [comment]
Done here #369
