### ISSUE TITLE
Get Foreign PDF link doesn't work

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#375]
http://syncids.com/GetXForeignPDFs.asp?FirmName=goedkencom&ClientNumber=TEST&Quantity=10
This is how we push for PDFs after a migration.  

I change the domain name, ClientNumber, and Quantity for each migration.

**Comment by ntgn81** [comment]
@JulieJager , I have a fix for this. Can't access the box from work though. I'll get it in in the evening. Do you need it now?

**Comment by JulieJager** [comment]
@ntgn81 This evening is fine.  Thank you.

**Comment by ntgn81** [comment]
@JulieJager , should be fixed now.

**Comment by JulieJager** [comment]
Seems so.  Thanks so much!
