### ISSUE TITLE
SyncIDS IDS Form

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#376]
Add the SyncIDS IDS form to the ZIP folder as is.  That is, do not currently change the Cite Numbering until we know more about what our clients want.  Currently, cite numbering is continuous from section to section whereas the EFS-Web fillable IDS form restarts numbering to 1 from section to section. 

Thank you!!

**Comment by ntgn81** [comment]
@JulieJager , so you don't want the numbering to reset to 1 upon section change?

**Comment by JulieJager** [comment]
@ntgn81 I'm changing my mind.  I **do** want the numbering to restart at 1 in each section.  I will deal with the customer who likes the current continuous numbering to learn more about her needs.  Thanks for double-checking.

**Comment by ntgn81** [comment]
Okay, I'll close this one until you decide otherwise :)

**Comment by JulieJager** [comment]
@ntgn81 Does that mean the SyncIDS IDS form is available?  The fact that you are closing this?

**Comment by ntgn81** [comment]
Oh my bad, was thinking about EFS form

**Comment by ntgn81** [comment]
@JulieJager, very first version is out in dev.syncids2.com

I added `Download SyncIDS` options. Ignore the file name (syncids.pdf) for now. I was just working on the content.

**Comment by JulieJager** [comment]
Very happy to see this form.  Looks great!  Seems to work properly.  I will provide specific comments soon.  I will test to see if the form uploads properly to EFS-Web.

**Comment by JulieJager** [comment]
Looks like we just need a few that you are probably already aware of, I just wanted to get it on a list:
1.  Transmittal Letter needs to be generated in both Download SyncIDS Form w/ and w/o references
2.  PDF naming convention needs to include Client-Matter (e.g., Acme-009-Foreign-1, Acme-009-NPL-2)
3.  PDF naming convention needs to change "other" to "NPL".

**Comment by ntgn81** [comment]
Don't you want the docs to be ordered by the order they appear in the ids form? Having the order index at the beginning would do that.

**Comment by ntgn81** [comment]
Maybe not, since Foreign comes before NPL alphabetically anyway :)

**Comment by JulieJager** [comment]
:) However we are doing it with the other IDS form is great with me. :)

**Comment by ntgn81** [comment]
@JulieJager , done and pushed to production
