### ISSUE TITLE
Invoice Hard Coding not working | Pabstpatent.com

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#377]
@ntgn81 PabstPatent.com has some hard coding instruction that say john@pabstpatent.com is supposed to receive all immediate invoices generated but that is not happening.  The user is getting the invoice only.  

Please take a look when you can.

**Comment by ntgn81** [comment]
@JulieJager  Does john@pabstpatent.com receive them as `cc`, or as sole receiver?

**Comment by ntgn81** [comment]
@JulieJager , should be fixed now

**Comment by JulieJager** [comment]
TO:  and sole receiver

**Comment by JulieJager** [comment]
Thanks! I'll keep any eye on this. :)
