### ISSUE TITLE
De-Duplicate Language

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#378]
@yneves Please add a ? to the De-Duplicate feature in the NPL section (similar to the Timing/Statement Section in the dashboard) and add the following language when users hover over the ?:  Click De-Duplicate to reveal the SyncIDS NPL serial numbers and to learn more about this feature.

When a user clicks De-Duplicate, reveal the NPL serial number (we already do this) and add a Pop-Up Window with the information I am sending via email.  Please include an OK button to exit the window. 

Thank you!

**Comment by yneves** [comment]
Done here #380
