### ISSUE TITLE
Update New UI to not grant ability to accept a space in matter name

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#379]
Looks like pabstpatent.com created two identical matters but one has a space in it.

![capture5](https://cloud.githubusercontent.com/assets/17907226/16770319/15f52286-4812-11e6-883b-aaa6ef80d2df.JPG)

It is causing a problem when user is trying to create an IDS in the old UI.  Old UI only shows the matter with 0 uncited references.  Before I delete the duplicate matter, I wanted you to see this.  Please let me know when you are done so I can delete the erroneous matter. Thanks.

**Comment by JulieJager** [comment]
Actually, it looks like the matter with the 25 uncited references includes a space in the name.  I now see it in the old UI.  I will continue to investigate.

**Comment by yneves** [comment]
Spaces blocked now. Done here #389
