### ISSUE TITLE
Matter creation - a way to specify source matter to copy details from

### ISSUE THREAD

**Issue by ntgn81** [syncids/syncids-ui#384]
Julie, can you specify what exactly gets copied over, please?

@yneves, probably just another autosuggest box inside "creation confirmation" modal to enter source matter? Or something easier.

**Comment by JulieJager** [comment]
Per customer's request, copy over:  

First Inventor
Email
Full Name
Reg #
Apply E-Signature
Priority Date
Examiner Name
Two-Way Related Matters
One-Way Related Matters
Sync With Categories
Notes

In other words, everything except Application #, Art Unit, Filing Date, and Matter Closed.

**Comment by yneves** [comment]
Done here #468
