### ISSUE TITLE
URGENT BUG REPORT:  FOREIGN section, citing documents

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#385]
REPORT from rplotkin.com:

**Second email**: 
The bug is actually worse than I thought.  In addition to jumping back to the top of the screen, SyncIDS clears the “Cited” checkbox.  Therefore I am actually not able to check off Foreign Patents as cited. 

I am running Firefox 47.0 on Windows 7.

The matter I am working in is M0002-1028C2.  Could you please look into this and also check off all of the Foreign Patents for me?

=====================
**First email**:  
When I check off foreign references as cited, sometimes SyncIDS jumps back to the top of the web page.  Then I have to scroll back down to the Foreign References section to keep checking off more references.
[not sure why this text is so big]
This is only seeming to happen with foreign references and it doesn’t happen every time I check off a reference, but it is disconcerting.
====================
From Julie:  This is happen in the syncids.com database too.  All web browsers are affected.

**Comment by ntgn81** [comment]
@JulieJager , can you ask them to use Chrome for now, and see if the issue still persists?

**Comment by JulieJager** [comment]
@ntgn81 Sure.   Also, I noticed one foreign reference does not include a leading zero in the backend.  Could this be causing a problem?

![capture5](https://cloud.githubusercontent.com/assets/17907226/16812720/0548dfc6-48f4-11e6-8469-4082c9824f7c.JPG)

**Comment by JulieJager** [comment]
@ntgn81 Actually, I am using Chrome and I am experiencing the same problem the customer is.

**Comment by ntgn81** [comment]
@yneves, it's triggering re-rendering of the whole document section when a single document changes. Can you take a look at this, please?

**Comment by yneves** [comment]
I will check in a bit.

**Comment by yneves** [comment]
Fixed here #387

**Comment by JulieJager** [comment]
Glad you figured it out!  I will test in Production.  :)

**Comment by ntgn81** [comment]
@JulieJager , can you check production now? it should be out

**Comment by ntgn81** [comment]
Okay, it's there now

**Comment by JulieJager** [comment]
It is still not working.

**Comment by ntgn81** [comment]
Refresh again please, youmight have old code

**Comment by JulieJager** [comment]
IT'S WORKING!  Thank you all!

**Comment by ntgn81** [comment]
Wooo
