### ISSUE TITLE
Low priority: Comments column resizing

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#386]
I noticed in some instances, the comments column shrinks in size.  Not sure how this is happening.  I'll try and pin point a reason if I can. 

![capture5](https://cloud.githubusercontent.com/assets/17907226/16812592/639b7ad0-48f3-11e6-91eb-ded63ec430bf.JPG)

**Comment by yneves** [comment]
I think this was happening when you drag (by accident or not) the resize corner of the input box (bottom/right). I had this disabled. Done here #391
