### ISSUE TITLE
Dashboard, Page Size section

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#399]
Filter was set to large amount of data, I visited page 14 of the results.  
I then changed my filter information to resolve a smaller amount of data.  When I did that, it was as if my view was still at Page 14 even though my new filter did not result in 14 page of data.  

Result was I saw no results in the dashboard.  I hope this makes sense.

**Comment by ntgn81** [comment]
Yep, @yneves , looks like we're not resetting the page number upon todoList change.

It should reset to page 1 if the new page count is greater than the current page.

**Comment by yneves** [comment]
Fixed here #401
