### ISSUE TITLE
Add column to SQL re combining Full Name and Reg. No. in e-signature

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#417]
@ntgn81 We have a customer: Shun Yao (shun@parklegal.com) who wants his Reg. No. included in his e-signature:  /Shun Yao, Reg. No. 59,242/

Currently, our e-signature are listed as:  /Shun Yao/

Jim thought we could add a column to SQL that is entitled: Reg. No. in Signature? (or the like) and have Yes or No in each cell.  To start, we would have Shun Yao as a "yes" so he sees his e-signature in the IDS form(s) and Transmittal Letter like this:
 
![capture5](https://cloud.githubusercontent.com/assets/17907226/16993843/b04ac742-4e6a-11e6-9631-e5b366afe630.JPG)

This would not be something that user could choose in the UI at this time.

**Comment by ntgn81** [comment]
Sure. Do you see it as a feature other users would want? I don't see it as a hard thing to add to UI.

**Comment by JulieJager** [comment]
@ntgn81 Thanks.  We do not currently know if other users want but we're thinking we should be prepared if we receive more requests.  Do that answer your question?

**Comment by ntgn81** [comment]
Sure. I just wanted you to know that it's easy to add that to UI :)a

**Comment by ntgn81** [comment]
@JulieJager , hmm his `ApplyESignature` flag is false, how is he getting that? Or did he just turn it off?

**Comment by JulieJager** [comment]
@ntgn81 This customer just received the new UI.  They will check the apply e-signature box if his name and reg no. can be combine.  If not, they did not plan to check the box but rather manually type it in to each IDS.

**Comment by ntgn81** [comment]
@JulieJager , done!

**Comment by JulieJager** [comment]
@ntgn81 It's perfect!  Thank you. It is so nice having you and @yneves in our corner!  Thanks for your expertise and quick-turnaround. :)

**Comment by JulieJager** [comment]
@ntgn81 Customer is requesting a minor change:  Replace No. with #
/Shun Yao, Reg.# 59242/

**Comment by ntgn81** [comment]
@JulieJager , it should already be updated with that

**Comment by JulieJager** [comment]
@ntgn81 I should have tested before setting this up.  Thanks!
