### ISSUE TITLE
Auto Create an account for syncids when a new firmname is created

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#418]
Currently, when a new FirmName is created, the software automatically creates a SyncIDS account as well.

syncids@company.com with the Password as T******2

Could we enjoy this autocreation in the new UI as well?  NO RUSH!  Thank you.

**Comment by ntgn81** [comment]
I believe we already have that logic. The difference is that the new account is not created when firm is created, but when you go in and try to login with syncids@firmname.com
