### ISSUE TITLE
Food for Thought: NPL Serial Nos. and DeDupping

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#419]
Jim and I were talking and we are trying to figure out a better way to De-Dup NPLs.  Right now, our users need to know the NPL serial numbers to replace losing descriptions with winning descriptions.  We were wondering if you can come up with a better way to replace losing descriptions with winning description from the UI.  We believe our users should not ever have to see the NPL serial numbers.  

No rush.  We just wanted to get you thinking about an improvement here.  Our users are used to doing the way it is now so, again, no rush to improve at this time.

**Comment by yneves** [comment]
![image](https://cloud.githubusercontent.com/assets/5215669/17072791/5eba8d9e-5041-11e6-8007-4769a8e2113e.png)

**Comment by yneves** [comment]
@JulieJager @ntgn81 That's my idea. Basically when you click to deduplicate in the gear icon, it shows this modal with the Losing Description filled so you can enter the Winning Description (with suggestions). There should be more text explaining what this is about, probably most of what we have in the help modal. What do you think?

**Comment by JulieJager** [comment]
@yneves I like that.  Keep in mind too that users could first click on the winning description and want to pick the loser.

**Comment by ntgn81** [comment]
@yneves , this is a great start! I wonder if we can give them multiple options to select from?

**Comment by yneves** [comment]
It's simple i guess, let start with one and see how it goes. Added a button to switch losing/wining. 

![image](https://cloud.githubusercontent.com/assets/5215669/17156739/c3c83dc6-5361-11e6-8843-a9d419a67085.png)

**Comment by yneves** [comment]
@JulieJager I'll show how its working on our Thursday call and we can adjust what's needed.
