### ISSUE TITLE
HIGH PRIORITY: Advanced Feature: Warning users 

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#422]
BACKGROUND/PROBLEM: 
As it stands, users can generate an IDS for a matter without realizing not all references made it to the IDS form.  As you know, SyncIDS holds back uncited references when not all required fields are met (PDF, Document Number, Date, Inventor or CC).  Our users want some sort of warning before they generate an IDS that the matter they are working on is missing required information in the Documents Section.

Initially, we were thinking a pop-up after a user tries to generate an IDS by clicking the gold folder, but pop-ups can get annoying after awhile since sometimes they know required information is missing.  

PROPOSED SOLUTION?
If any uncited document number is missing any required information, then the font color of the number of uncited references in the dashboard should be red.  Additionally, in the Documents title bar, maybe we can list the number of uncited references that are missing required information, as a warning? 

Of course, please feel free to brainstorm your own ideas as well.  Thanks!

**Comment by ntgn81** [comment]
@yneves , yeah, this definitely need some brainstorming.

Todolist only looks at matterdb. We'll need to go out to documentdb to get the status of each document.

**Comment by yneves** [comment]
Another approach would be maintaining an `incompleteArt` field witha a list of incomplete documents, not sure how hard it would be though.

**Comment by JulieJager** [comment]
Any solutions on this one yet?  That is, warning a user that some required fields in the Documents Section are not fulfilled?  Could we change the color of the text associated with a matter in the Dashboard?  Or a popup when generating the IDS?  Or a button to have Syncids check?  Just some ideas.

I noticed in the US section that Inventor is not marked as a required field.  FYI:  PDF, Document Number, Date, Inventor/Country Code are all required.  Thanks!!

**Comment by ntgn81** [comment]
I  think the most optimal way we can do is to notify users when they try to file the matter. Having to query all the documents for every matter and check their statuses might be too much.

**Comment by JulieJager** [comment]
We kind of do this at the File button stage already.  That is, if any refs do not included required field, they are left behind as uncited.  Unfortunately, at that stage, the user already filed the IDS with the USPTO.  So, they found out too late that the IDS form was missing a document.

**Comment by yneves** [comment]
I started working on an API for this, but definitely not good to fetch this information every time.

**Comment by JulieJager** [comment]
Draft language to start with.  Please feel free to amend.

**WARNING** [in red]
# of uncited references missing required fields: 10
Required: PDF, Date, Inventor or CC [smaller font if able]

**Comment by yneves** [comment]
![image](https://cloud.githubusercontent.com/assets/5215669/18854369/46fa8114-8421-11e6-8bd0-d1d60bfbbb4d.png)

**Comment by yneves** [comment]
![image](https://cloud.githubusercontent.com/assets/5215669/18854378/58714518-8421-11e6-9dac-23036a382dd5.png)

**Comment by yneves** [comment]
![image](https://cloud.githubusercontent.com/assets/5215669/18854392/6ef7f084-8421-11e6-86ef-27da7fa4c43b.png)

**Comment by yneves** [comment]
@JulieJager check it out!

**Comment by yneves** [comment]
Done here #580

**Comment by JulieJager** [comment]
Love, love it!! Great job! My only suggestion would be to rephrase "Checking Consistency....". Can we be more specific?  "Checking for Missing Fields..." or something like that.

**Comment by ntgn81** [comment]
Beautiful stuff! Yeah, how about

- `Validating uncited references...`
- `There are x uncited references that are missing required fields`
