### ISSUE TITLE
RUSH:  Need to translate periods (.) in Matter Names to hyphens (-) when naming PDFs

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#427]
Seems our PDFs are not being uploaded to the USPTO's EFS-Web systems where there are periods in the naming. 
Example:  Customer: parklegal.com
Client: BRCD
Matter:  Any matter (not reported)

See reported issue below:                  
Hi Julie - Sorry to bother you but we ran into a bit of an issue today with BRCD.  Unfortunately, the docket numbers contain periods in them and in the new SYNC, it generates the docket number followed by a letter (for example Brocade-BRCD-3160.1.US.DIV-IDS-A).  We are unable to upload any of the references due to the naming conventions of the USPTO (can’t contain any periods).  Is there a way to put dashes instead of periods or possibly only use the first part of the docket no. (for example BRCD-3160-IDS-A)?  Tia is going to use the old SYNC to download the references for this docket no. so she can upload the IDS today.  Also, can we change Sean’s signature to read - /Shun Yao, Reg.# 59242/ -?  Please let me know if you have any questions!

**Comment by ntgn81** [comment]
@JulieJager , done for file names and signature, can you check it out please?

**Comment by JulieJager** [comment]
Looks good!  Looks like you are replacing . with underscores.  Perfect

**Comment by ntgn81** [comment]
Oh yeah, did you want `-`?

**Comment by JulieJager** [comment]
No, underscore is just fine
