### ISSUE TITLE
Cannot Add new matter to Two-Way Sync With Matter box

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#433]
The ADD button does not seem to work in the Two-Way Sync with Matters box.

**Comment by yneves** [comment]
@JulieJager Do you have anymore info on this? It's working for me.

**Comment by JulieJager** [comment]
@yneves I am adding an existing matter but I get the failed status tag:  

![capture](https://cloud.githubusercontent.com/assets/17907226/17117414/937983a4-5281-11e6-8749-59edd53e3bf5.JPG)

**Comment by ntgn81** [comment]
@JulieJager , should be fixed now, please let me know if you still have the issue.

**Comment by JulieJager** [comment]
Seems to work.  Thanks guys!  You're the best!
