### ISSUE TITLE
LOW PRIORITY:  Fix Height of Two-Way Sync box, or the like

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#439]
@yneves I believe we talked about this previously.  Let's see what creative way you can fix the width of the Two-Way Sync Matter box, or show only a few lines and then a MORE... button to see the rest, or the like.  Some of our customer's are experiencing extensive rows in this section because it is listing all its matters.  For examples, you may log into any BRCD matter in the parklegal.com database. 

This may also solve the problem where when the Client and Matter section is closed, it is somewhat clunky while closing...doesn't seem to close at the same time.

Thanks!

**Comment by yneves** [comment]
![image](https://cloud.githubusercontent.com/assets/5215669/17193600/43cb28d0-542a-11e6-8d7f-f899bc056c1a.png)
![image](https://cloud.githubusercontent.com/assets/5215669/17193617/51911c54-542a-11e6-97fc-8fb706cd2ff5.png)

**Comment by yneves** [comment]
@JulieJager Check it out, i made it a dropdown and moved the buttons inside, what do you think?
