### ISSUE TITLE
Batch Upload Feature in the US Section

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#440]
I believe you stated earlier we have the ability to batch upload in the US section, but I am not sure how to do that ... to test.  In the old UI, we added a semicolon to the first empty cell to enter into batch entry mode. Thereafter, a user can paste in mess data which may have several patents or publication listed.  Thereafter, SyncIDS would search that data for any 7 digit or 11 digit numbers (or the like).  Then, it would take a trip to espace to resolve the date and inventor name.  Can we do something like?  No rush, just documenting at this point.  Thanks!

**Comment by ntgn81** [comment]
Nopes, we don't have such functionality yet.

**Comment by yneves** [comment]
don't sort, show original to compare, read `2002/`
