### ISSUE TITLE
REPORT FROM CUSTOMER:  Matter not being removed from To-Do List after filing

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#441]
REPORT: 
From: Niels Haun [mailto:nhaun@ddhs.com] 
Sent: Tuesday, July 26, 2016 11:48 AM
To: Julie SyncIDS <julie@syncids.com>
Subject: RE: SyncIDS 4.0 Launch | Recorded Session - Link to New UI (Beta Version)

Hi Julie.  I have noticed that upon “filing” an IDS the matter is not removed from the listing at the top.  In the prior interface, I thought a filed matter was automatically removed from the list.  
See below 5507US2 was just “field” – 0 uncited. (note I do not have “show all” checked.)
![capture](https://cloud.githubusercontent.com/assets/17907226/17147237/917bc1a6-5327-11e6-9185-2a3d9f03240b.JPG)

**Comment by yneves** [comment]
@ntgn81 When the matter is filed, the API still returns it, so it remains in the list even if i refresh. Also there's nothing in the JSON to indicate its been filed. I guess `matterClosed` should be "ON" in that case, no?

**Comment by ntgn81** [comment]
Yep, i'll look

**Comment by ntgn81** [comment]
@JulieJager , should be fixed now.
