### ISSUE TITLE
REPORT FROM CUSTOMER: Unable to File

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#442]

**Comment by JulieJager** [comment]
REPORT BELOW:

From: "Jennifer Sanborn" <jenny@parklegal.com>
Date: July 26, 2016 at 11:53:49 AM CDT
To: "'Julie SyncIDS'" <julie@syncids.com>
Cc: <syadmin@parklegal.com>
Subject: "Failed to File Matter" error
Reply-To: <jenny@parklegal.com>

  I filed several IDS’ today and when I clicked file & confirm, they all said “Failed to file matter”.  The docket numbers are as follows:
 
P260-1NUS
P65-1NUS
P142-1NUS
P50-2NUS
P64-1NUS
 
                Please let me know if I need to do something else!

**Comment by yneves** [comment]
@ntgn81 @JulieJager This other issue #441 explains this one too. Since the matter remains in the list even after a refresh, the user is trying to file it again, and its failing. It happened to me while testing the other issue.

**Comment by ntgn81** [comment]
@yneves , great catch! I fixed the other issue, this one should be fixed too
