### ISSUE TITLE
REPORT FROM CUSTOMER: PDFs will not download in specific matter

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#443]
REPORT BELOW:

From: "Donaldson, Ashley" <Ashley.Donaldson@btlaw.com>
Date: July 26, 2016 at 12:34:36 PM CDT
To: Julie SyncIDS <julie@syncids.com>
Subject: RE: SyncIDS 4.0 Launch | Link to Recorded Session - Link to New UI (Beta Version)

Thank you for your time this morning, and my apologies again for being late to the meeting. I love the new UI! So much more streamlined and quick! It’s excellent J One quick thing, our matter 5723-253047 has 689 uncited references. When I try to download the file with the references, I get a failure notice. I can download the IDS’s without the references just fine though. Is it due to the amount of references?

**Comment by ntgn81** [comment]
That's right, the amount of references is killing the service. I'm looking into it

**Comment by JulieJager** [comment]
I think I found the problem here:  I cannot view through the UI the largest PDFs in this matter.  We need to be able to resolve any size.  Snapshot of the PDFs I cannot view: 

![capture55](https://cloud.githubusercontent.com/assets/17907226/17220659/cf654688-54b5-11e6-8c61-2deeb7d660ea.JPG)

**Comment by ntgn81** [comment]
@JulieJager , what are you getting when you tried to view them?

**Comment by JulieJager** [comment]
![capture55](https://cloud.githubusercontent.com/assets/17907226/17228505/e53ca334-54d8-11e6-827c-452e31ac490e.JPG)
