### ISSUE TITLE
NPL is erroneously allowing literal duplicates

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#444]
@yneves Currently, in the NPL section, the UI is allowing literal dups.  I copy/pasted a description into a new cell and it did not tag it as a duplicate.

**Comment by yneves** [comment]
@JulieJager Any specific details? It's working for me.

**Comment by JulieJager** [comment]
@yneves Sure.  If you copy/paste an existing NPL into a new cell, SyncIDS allows it. 

![capture](https://cloud.githubusercontent.com/assets/17907226/17158196/26169a3e-535a-11e6-90c1-0b2d29fe6dfa.JPG)

**Comment by yneves** [comment]
@JulieJager It's possible that it's an extra space or line break, which is invisible. I'll strip them before saving, should fix it. If its the exact same content, i get the duplicate response.

**Comment by yneves** [comment]
Done here #445

**Comment by JulieJager** [comment]
@yneves Thanks!
