### ISSUE TITLE
REPORT FROM CUSTOMER:  Need to Auto-Suggest at Client level (not matter level)

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#448]
I believe this is what our customer is reporting:  

REPORT FROM CUSTOMER:  
When using the new interface, the pdf for an existing NPL reference in the database did not copy over to a new matter.

I created new matter CXR307.AUP.  In the NPL, I entered “Bruder…” and the system gave me the option of clicking on the entire text from the pre-existing reference, which I did.  I then hit tab.  The reference already exists in matter CXR307.PCT.  The text populated but the existing pdf did not.  I notice the system added the reference in CXR307.AUP as NPL329.  The already existing reference is NPL155.  I did not change any text so I don’t know why it became a new NPL reference.  I de-duped it to make it the existing reference but in the old interface it would recognize it as the same reference if I followed the procedure I state above.

**Comment by yneves** [comment]
Waiting for API for this one. @ntgn81
