### ISSUE TITLE
New Tab: Customers

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#451]
@yneves As we discussed, please create a new tab called, "Customers" and enter (in a cool way) the following language:

Over 1000 companies rely on SyncIDS to prepare their IDSs quickly and accurately.  Here are a few of them:

Also, please include the attached logos, or, if for any technical reasons these do not work, please feel free to locate and extract a different version via the web.  If I can assist in any way, please let me know.  Thanks!!
[Logos.zip](https://github.com/syncids/syncids-ui/files/394241/Logos.zip)

**Comment by yneves** [comment]
@JulieJager looks like something is wrong, there is only one logo at this zip

**Comment by JulieJager** [comment]
@yneves   Oops.  Trying again. 
[Logos.zip](https://github.com/syncids/syncids-ui/files/395027/Logos.zip)

**Comment by yneves** [comment]
![image](https://cloud.githubusercontent.com/assets/5215669/17345960/f5f3f24a-58de-11e6-932b-5192100ebfcf.png)

**Comment by yneves** [comment]
@JulieJager I really suck as a designer, so i'm going to need some feedback and suggestions, but the base is done.

**Comment by yneves** [comment]
I made so every time you refresh the page the logos get sorted randomly so always look like something new.

**Comment by JulieJager** [comment]
@yneves LOOKS great to me.  Just enlarge the text a bit and its good!

**Comment by yneves** [comment]
Done here #454
