### ISSUE TITLE
MEDIUM PRIORITY:  Filter will not find matters with - or ()

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#452]
@yneves Regardless if show all is checked the following matters will not list in the dashboard unless the hyphen and text thereafter is removed:

parklegal.com
Search matter P64-1NUS
No results even if show all is checked
Search matter P64 
results show properly.

**Comment by yneves** [comment]
I checked and the query string is being sent correctly, must be at server side. @ntgn81 

`Request URL:https://syncids-api-int.herokuapp.com/api/todos?firmName=toptalcom&q=006-NEW&showAll=false&loginEmail=yuri%2B666@toptal.com`

**Comment by ntgn81** [comment]
@JulieJager , this seems to be an existing problem. What do you think should happen here? I think it's a bit ambiguous on what should happen

**Comment by JulieJager** [comment]
@ntgn81 Let's discuss this on our next call.  Jim may be able to explain this better than I can. :)

**Comment by JulieJager** [comment]
Here is an example:  I am searching for matter: 60509-US but Show All doesn't find it.  I have to remove the hyphen and US to find it.
database: itwcom
client: welding

**Comment by ntgn81** [comment]
@JulieJager , yep. This is the expected outcome right now, as `-` is considered client-matter separator, similar to pipe `|`.

Do we want to remove `-` as client-matter separator since some matters have `-` in their names?

**Comment by JulieJager** [comment]
Yes.  Remove - as a separator.  We have trained our users to use the pipe symbol. 

Will a fix also include the issue with () in matter names?  

Example matter name:
LawFirmMatterNumber(Client MatterNumber)
12345US(6789P)

Sometimes, for their billing purposes, they want both numbers listed.

**Comment by ntgn81** [comment]
@JulieJager , which firmname has matter with name `12345US(6789P)` ?

**Comment by JulieJager** [comment]
itw.com is a good example:

![capture](https://cloud.githubusercontent.com/assets/17907226/19543359/7c75d6c2-963c-11e6-90a6-e202a9a14545.PNG)

**Comment by ntgn81** [comment]
Seems to be working for me
<img width="778" alt="screen shot 2016-10-19 at 9 51 01 pm" src="https://cloud.githubusercontent.com/assets/4622542/19543528/2c99f96c-9646-11e6-9831-4e424e9824da.png">

**Comment by JulieJager** [comment]
Weird.  It must have been user error (me) previously.  Thanks!!
