### ISSUE TITLE
Removal of ClientNumber from IDS form

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#460]
@ntgn81 

Parklegal and novelip have requested that the ClientNumber be removed from the Attorney Docket No. shown in the EFS-Web IDS form.  Is this possible on a firm-by-firm basis?  Typically, our users want this combination but it seems some do not.  

Example:  novelip wants RAPISCAN removed from the string:

![screenshot](https://cloud.githubusercontent.com/assets/17907226/17484073/0796b776-5d4e-11e6-8e5c-1df3f077c306.png)

**Comment by ntgn81** [comment]
Sure, we can do that. I think we need an organized way to keep these customizations (based on firm, client, attorney, etc..)

**Comment by ntgn81** [comment]
@JulieJager , done

**Comment by JulieJager** [comment]
Thanks, @ntgn81 .  I agree we need to organize these custom requests.  I can create an excel, word, or we could keep an "issue" open entitled: Custom Requests, or the like.  We have to both be able to access.  Thoughts?

**Comment by JulieJager** [comment]
I tested the removal of the clientnumber.  All looks good here.  Thanks again!

**Comment by ntgn81** [comment]
Yep. I think an issue here is fine, just so we don't have to go through code to find them.
