### ISSUE TITLE
Default Cursor position

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#462]
@yneves In U.S., foreign and NPL sections, after entering a document number and the date and inventor/cc and applicant AUTO resolve, can we have it so the cursor defaults to move to the next row?  The empty row.  This is so users do not have to tab or use their mouse to enter get into the next empty cell.  If the date, inventor/cc and applicant did not resolve, the cursor should move to the next empty cell as it does now.   Thanks!!

**Comment by yneves** [comment]
Done here #465
