### ISSUE TITLE
URGENT:  NPL descriptions not matching up with PDFs

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#467]
I tried to solve this issue, but cannot seem to from my angle.  See pabstpatent report below:

Please note this is the same client that reports the spaces disappearing from the descriptions.  What I did notice is one description has seem to override original descriptions somehow:  

![capture](https://cloud.githubusercontent.com/assets/17907226/17536226/20a27e74-5e59-11e6-9d09-044e5bed5fa1.JPG)

Julie,
I tried to click on a reference in LIQ103CON, OTHER, “HALAL TheChemistry of Haircolor” and it tells me “Document not available”.  Is there an issue in SyncIDS?  

Also, I have clicked on some other references and they were not the actual reference, they were other references.  Like they were jumbled up.  Examples below.

For example: in OTHER - THERMOFisherScientific,"BismaleimideCrosslinkers(BMOE,BMBandBMH)",productinstructions,pages1-3(2012).  I viewed this pdf & it is actually a Third Party Anonimous Submission.
SALVIN, et al. "Biological surface modification by " thiol-enel addition of polymers synthesized by catalytic chain transfer polymerization (CCTP)" , Polymer Chem., 3:1461-6 (2012).  It is actually the Thermo Scientific Instructions.

Do you know what could have happened, or can this be fixed?

**Comment by JulieJager** [comment]
In addition, client reported earlier today she could not generate the excel.  I looked and saw clientdb showed liq as the client not LIQ, so I updated it and the excel work.  But now, I see the clientdb refers to it has liq again.  How is that changing?

**Comment by ntgn81** [comment]
@JulieJager , do you remember what you did before it changed back? Or it was just after awhile?

**Comment by ntgn81** [comment]
And for the pdf issues, I'm not able to pin-point the problem. Can it possibly be because she uploaded the wrong pdf?

**Comment by JulieJager** [comment]
I don't think she uploaded wrong PDF because several are mismatched.  All I did after I changed the ClientNumber to LIQ was generate the excel report. If you notice, all the spaces are gone too and some include code.

**Comment by ntgn81** [comment]
@JulieJager , looks like those 3 duplicate NPLs were created from the old UI, around 2 years ago

**Comment by JulieJager** [comment]
It seems several of these NPLs are literal duplicates and non-literal duplicates.  Some of the dups were created without spaces.  Hard to explain in this forum.  

I was able to enter several literal duplicates.  I dedup and picked the later NPL serials #s as winners in hoping to remove some issues with the losing NPLs.  What happened then was SyncIDS did not keep the PDF.

**Comment by JulieJager** [comment]
@yneves literal dups are able to populate and when I dedup out old NPLs, autosuggest still lists them?  I thought we fixed these problems previously?  It seems as though we rolled back somehow.

**Comment by yneves** [comment]
@JulieJager I'll check and make sure it's fixed!

**Comment by yneves** [comment]
@JulieJager I fixed it to remove the description of losing document after dedup here #468 , i think it's the first time i fix it, don't recall doing it before. I still can't enter duplicate entries, tried in many different ways. Can you show me on thrusday meeting?

**Comment by JulieJager** [comment]
@yneves Thanks.  Example:  Enter NPL50 into a new cell and you'll see software allows it.
See FirmName: pabstpatent.com
Client: LIQ
Matter: LIQ103CON
NPL50

Also, the spaces in the U.S. Inventor Name field and NPL fields keep getting removed from this matter or client database for some reason.  I put them back in (for the 3rd time).  I will not put them back in the next time so you can see what's happening, maybe.

**Comment by yneves** [comment]
Yeah, i can see now. The document is added with a different serial number (NPL62). This looks like a server issue, clearly they are the exact same description. Any idea @ntgn81?
