### ISSUE TITLE
Boxes/Fields are resizing when user is unknowningly dragging cursor

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#469]
@yneves I'm pretty sure we fixed this previously but it's occurring again.

![capture](https://cloud.githubusercontent.com/assets/17907226/17543037/479bc96a-5e93-11e6-941f-ca18b03c65b3.JPG)

**Comment by yneves** [comment]
@JulieJager Yes, we did, but production site was updated last time 7/20. Any reason to wait so long @ntgn81? Lot's of improvements didn't make production yet.
