### ISSUE TITLE
URGENT:  Fields in Matter section are going over section

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#474]
@yneves I have a demo today at 12:00 CT.  Could we get this fixed before then?  

![capture](https://cloud.githubusercontent.com/assets/17907226/17622377/9b3f411e-605f-11e6-8c5f-6017058853c5.JPG)

**Comment by yneves** [comment]
@JulieJager Yeah, i'll try to get it fixed before it.

**Comment by JulieJager** [comment]
@yneves Thanks.  It seems wrapping text is not happening.

**Comment by yneves** [comment]
@JulieJager which browser is that?

**Comment by yneves** [comment]
@JulieJager just saw, it only happens in firefox, if you can use another browser on your demo, not sure if fix will make prod in time

**Comment by JulieJager** [comment]
@yneves I didn't realize it was only affecting firefox.  Looks fine in Chrome, Edge, IE.

**Comment by yneves** [comment]
Fixed here #472

**Comment by JulieJager** [comment]
There must be a bucket of things not rolled out yet because I just experienced this in Firefox?
