### ISSUE TITLE
NO RUSH.  Do not allow a sole matter in two-way sync box

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#477]
@yneves I think we fixed this once before.  When Matter 1 and Matter 2 are two-way synced and I remove Matter 2 from the group, the box should be empty, instead it lists Matter 1.

Client:  ABC
Matter 1:  Delete Matter 2 from the group while in Matter 1
Matter 1 remains in the group.

**Comment by yneves** [comment]
@JulieJager  In two-way sync, you can only remove the current matter from the group, i don't understand what you mean by "Matter 1: Delete Matter 2 from the group while in Matter 1". Can you explain more pls?

**Comment by JulieJager** [comment]
@yneves Nevermind.  This seems to be fixed now.  Previously, one matter could remain the two-way sync box, but now it doesn't.

**Comment by yneves** [comment]
ok!
