### ISSUE TITLE
U.S. DeDuping issue

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#479]
btlaw.com
Client: 6427
Matter: 225119

LOSER:  U.S. Doc 4479379 was Uncited
WINNER:  U.S. Doc 4478379 was Cited

I renamed loser to winner and UI deduped but it did not take on winner's cited status.

![capture](https://cloud.githubusercontent.com/assets/17907226/17751217/b24d56a4-648b-11e6-8a7f-6d28cc0c0dec.JPG)

**Comment by yneves** [comment]
Done here https://github.com/syncids/syncids-api/pull/10
