### ISSUE TITLE
HIGH PRIORITY: New info on why sometimes users can enter literal duplicates

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#480]
We currently have an issue where users can enter literal dups in the NPL section.  Jim believes its because of old coding vs. new coding.  For example:  

![capture](https://cloud.githubusercontent.com/assets/17907226/17752271/a521e2ba-6490-11e6-9187-9edb7006e5f5.JPG)

NPL22 was created via the old UI
NPL58 was created via the new UI

You can see the old UI generation includes Jim's coding and the new UI does not.  So the software thinks they are two different descriptions.  

![capture54](https://cloud.githubusercontent.com/assets/17907226/17752427/5f3513ca-6491-11e6-8669-e98813a19052.JPG)

@ntgn81 Is there a way for you write a robot to translate the old code to mimic the new database?

**Comment by ntgn81** [comment]
@JulieJager , thanks for the find. I'll look into it

**Comment by JulieJager** [comment]
Feedback:  "When you link several matters the non-patent documents are duplicated"

**Comment by ntgn81** [comment]
@JulieJager , can you please test this out? The fix is pushed

**Comment by JulieJager** [comment]
It properly dedups, status tag properly shows its a dup but UI leaves it as a ghost
![capture](https://cloud.githubusercontent.com/assets/17907226/18335109/5ae1176c-7542-11e6-92f2-25937b5486db.JPG)
.

**Comment by JulieJager** [comment]
Still need to roll out ghost NPL fix before I can close.  I think this Yuri fixed, just await release?

**Comment by ntgn81** [comment]
I just pushed out the latest changes. Can you give it another test, please? @JulieJager

**Comment by JulieJager** [comment]
Looks great!  Ghost references gone, batch uploading includes Design.  Yay!  One comment.  After clicking Confirm, I see the string of numbers in one cell separated by semicolon while its thinking.  Not sure I could see that before.  Not a big deal.  It still does what its suppose to do.  

@yneves CONFIRM button in Dedup is not working. Also, still requires users to tab out after picking a winner. I reported this earlier so you may still be working on it.

Thanks so much for your quick turnaround on these!  Sure makes my day a lot easier.  Demoing to several, several users today.  So were likely going to get hit hard in the next week or two.
