### ISSUE TITLE
Editing US Document Number

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#481]
@yneves If I edit a document number, I receive a pop-up that asks me to confirm the change.  If I say cancel, can we return the document number to its original state? 

For example, if I enter in Doc. No. 1 and change it to Doc. No. 2, and click cancel at pop-up window, SyncIDS currently leave Doc No. 2 in the cell.  Can we go back to original if cancel is clicked?

This would apply to all sections.  Thanks!!

**Comment by yneves** [comment]
Done here #482
