### ISSUE TITLE
Newly created category is not showing in Document Section tag

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#484]
I created Pens as a category but it is not listing in the category tag in the Document Section.

Also, when there is no categories and I click the Sync With Categories box in the Matter Section, an empty box is shown.

**Comment by ntgn81** [comment]
@yneves , the api seems to be returning the updated categories. Just the tags dropdown in documents not getting updated.

@JulieJager , they are added, a workaround for now is to refresh the page to see the tags.

**Comment by yneves** [comment]
I think i'll know what's going on, i'll fix it!

**Comment by yneves** [comment]
Done here #501
