### ISSUE TITLE
Cannot Create a New Matter

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#485]
I am getting a Failed status tag when trying to create a new matter for fitcheven.com. 

Client:  5569

I am launching the new UI to them in about a 1/2 hour.

**Comment by ntgn81** [comment]
@JulieJager , checking

**Comment by JulieJager** [comment]
Thanks.  Seems to be happening everywhere.

**Comment by ntgn81** [comment]
@JulieJager , can you try again, please?

**Comment by JulieJager** [comment]
Working.  Thanks for quick response.
