### ISSUE TITLE
Delete from Family / Delete from All Matters

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#490]
Nice surprise seeing the Delete from Family option.  Needs some additional work it seems.  I get a Failed Tag.  Also, I get a Failed Tag when trying to Delete from All Matters.

**Comment by ntgn81** [comment]
@JulieJager , should be fixed now. Can you give it another try?

**Comment by JulieJager** [comment]
It works! :)

**Comment by JulieJager** [comment]
The Delete from Family works but the Delete from All Matters does not.

**Comment by ntgn81** [comment]
@JulieJager , fixed. Sorry for that!

**Comment by JulieJager** [comment]
Look good.  Thanks so much!
