### ISSUE TITLE
Copy Data from Matter only copying over Inventor Name

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#491]
Also a nice surprise seeing this!  I like the functionality in the UI.  However, currently, it is only copying over the inventor name.

**Comment by yneves** [comment]
It's copying more information here, did you enter other info like notes, one/two way relations, filler? It's not copying art unit, filing date and mater closed, like you asked.

**Comment by yneves** [comment]
@JulieJager It's copying more information here, did you enter other info like notes, one/two way relations, filler? It's not copying art unit, filing date and mater closed, like you asked.

**Comment by JulieJager** [comment]
I'm a dork.  You are right!  So sorry!

**Comment by JulieJager** [comment]
@yneves Just testing and noticed this feature properly copies over two-way syncing instructions (I assume one-way as well) but doesn't add the new matter number to the family.  Can we do that?

Also, can we change button language from "Add to Group" to "Add to Family" ...to be consistent with "Delete from Family" in the Documents Section.

As always, thank you!!

**Comment by yneves** [comment]
Should be fixed now in dev site.
