### ISSUE TITLE
Batch Entry Mode \ WOW!

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#492]
Super cool, guys!!  Thanks, @yneves Love it.  Can you come up with a way for users to see how to enter Batch Entry mode, rather than the semi colon?

**Comment by yneves** [comment]
![image](https://cloud.githubusercontent.com/assets/5215669/17950052/196b68d2-6a2f-11e6-860d-b8dd7c6c270a.png)

**Comment by yneves** [comment]
Done here #500
