### ISSUE TITLE
HIGH PRIORITY: SyncIDS Form has embedded font

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#494]
![capture](https://cloud.githubusercontent.com/assets/17907226/17916509/909ba590-6979-11e6-994b-e3b67751f8dd.JPG)

**Comment by JulieJager** [comment]
Small change to form...I see you recreated it.  Great job.  It looks good.  We need "SyncIDS.com" in the footer.  Something with our name on it.  NO RUSH!

**Comment by ntgn81** [comment]
Yep, this might not be the right solution. I'll look more into why it's not accepted.

**Comment by JulieJager** [comment]
When I used to file these manually at the law firm, I would print the IDS as an image to avoid the whole embedded font requirements.  Just an FYI

**Comment by ntgn81** [comment]
Do you mean as png or jpeg file?

**Comment by JulieJager** [comment]
I would print as a(nother) PDF making sure the Print as Image box was checked.

**Comment by ntgn81** [comment]
Oh okay

**Comment by JulieJager** [comment]
Just to confirm, you are still working on this issue? We don't want our clients having to print as image. :)

**Comment by ntgn81** [comment]
Totally! Might need to fallback to the old code for now while I look for a better solution.

**Comment by ntgn81** [comment]
I switched to the old SyncIDS form generation. Should be in now. Can you give it a try, please?

**Comment by JulieJager** [comment]
Works!  No errors in EFS-web.  Cite numbering on form looks good too. :)
