### ISSUE TITLE
LOW PRIORITY: Hover language

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#496]
@yneves Can we add hover language to certain titles in the UI?  If so, I would like to add some hover language that describes what that feature does (per client feedback). 

Dashboard:
"**File**" column title:  "Tells SyncIDS you filed the IDS. Uncited references will be checked off as cited.  SyncIDS invoice generates."

Greyed out "File" button:  "Enter required data in Matter section."

"**IDS**" column title:  "Click folder to generate IDS with or without the references.  Uncited references with all required data fulfilled will flow to IDS form."

**"Migration" button**:  Yuri, save a copy of the "Legacy Data Migration" brochure here (already found in Services tab).  Name the dropdown menu choice:  "How to request a migration"

Custom IDS Paralegal Services and U.S. Office Action Sweeps brochures are transposed.  Please update links.

Client ID Section:
**"Billing Period"** title:  "Choose how frequently you want to receive SyncIDS invoices."

Document Section:
FOREIGN SECTION ONLY:  Change "Document Number" to "Doc. No. | Kind Code"
**"Doc. No. | Kind Code"** title:  "Add any sequence of numbers with or without Kind Codes (e.g., 2015055555, 2015055555A1, or 2015055555B2)."  

I will have more if we can do this.  thanks!! :)

**Comment by yneves** [comment]
@JulieJager Yes, definitely possible, you can keep adding more here and i'll include.

**Comment by yneves** [comment]
Done here #520
