### ISSUE TITLE
LOW PRIORITY: Add "Legacy Count" button to Client ID section

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#497]
Can we add next to the NEW button in the Client ID section a "Legacy Count" button.  Or anywhere else you deem appropriate.  

Currently, the number of legacy charges owed SyncIDS can only be accessed by SyncIDS employees through a URL.  When we update the URL with the FirmName and ClientNumber, the software gives us the latest number of migrations owed us (# Stored in the Clientdb). 

Since this button would be in the Client section, and we know the FirmName from log in, we should be able to have a pop-up with the number of migration charges still owed to SyncIDS for this Client.  Currently, this is what I see after updating the URL (see actual URL in screen shot):

![capture](https://cloud.githubusercontent.com/assets/17907226/17940403/89a791c4-69f4-11e6-8077-1f3a1922a1eb.JPG)

**Comment by yneves** [comment]
@ntgn81 Is this something we can add to the new API?

**Comment by ntgn81** [comment]
Totally

**Comment by JulieJager** [comment]
Cool! Maybe we can put something in the Migration button? Just a thought.

**Comment by yneves** [comment]
@ntgn81 Do you know what's the query to get this legacy count?

**Comment by yneves** [comment]
![image](https://cloud.githubusercontent.com/assets/5215669/18257294/93be9f02-7397-11e6-8e3d-76a784ee17dd.png)

**Comment by ntgn81** [comment]
I just realized that legacyCount already comes back as part of client data.

https://syncids-api-prod.herokuapp.com/api/todos?firmName=syncidscom&q=syncids.com&showAll=false&loginEmail=nam@syncids.com

**Comment by JulieJager** [comment]
Status?

**Comment by yneves** [comment]
Will work on it now.

**Comment by yneves** [comment]
It shows an info icon at top/right corner of client section containing `legacyCount` value. Only shows if its greater than zero.

Done here #616
