### ISSUE TITLE
Change Download IDS forms title

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#502]
@yneves Please update the titles as follows:

Download PTO IDS form only
Download PTO IDS form with references
Download SyncIDS form only
Download SyncIDS form with references

@ntgn81 Please update the IDS PDFs as follows:
Client-Matter_PTO_IDS-Form
Client-Matter_SyncIDS-Form

As always, thank you!!!

**Comment by yneves** [comment]
UI changed here #504

**Comment by ntgn81** [comment]
@JulieJager , all is done
