### ISSUE TITLE
LOW LOW PRIORITY:  New SQL column | Matter Reference First Entered in

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#503]
We already store the date a reference first enters SyncIDS in the artdb.  Can we add a column that includes the matter in which that reference was first entered?  This is important info our customers would like to know (where a reference was first cited).  I have additional considerations (exceptions) but just wanted to ask if this is even possible first.  Thanks! NO RUSH in responding.

**Comment by yneves** [comment]
@JulieJager It's totally possible, seems simple to do. What are the additional considerations?
