### ISSUE TITLE
Add instruction language to Batch Entry Mode

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#506]
@yneves As we discussed, please enter the following language in the Batch Entry Mode box that disappears after a user clicks in the box (or the like).  You can decide the best approach.  

"Type or paste in this box any amount of U.S. patent or publication numbers, in any format. Click PROCESS to clean and review data before entry."

**Comment by yneves** [comment]
![image](https://cloud.githubusercontent.com/assets/5215669/18020528/2737d902-6bb8-11e6-8b51-f4d91e5a6517.png)
Done here #508

**Comment by yneves** [comment]
Also added help icon with similar text.
