### ISSUE TITLE
NPL Deduping Description needs work | Return NPL serial number reveal

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#509]
When I click "Switch Losing/Winning" the description just gets copied.  
![capture](https://cloud.githubusercontent.com/assets/17907226/18030179/f0e7851c-6c72-11e6-808d-8fc14ea75cfa.JPG)

Also, can we turn back on the NPL serial number reveal column somehow.  Maybe its own action in gear icon?  I need to know the NPL serial number associated with the descriptions because the backend only lists the NPL serial numbers in the matterdb.  I'm having a hard time matching NPLs to descriptions.  Thanks!!

**Comment by yneves** [comment]
Fixed switch button here #516. I will add serial number back somehow.

**Comment by yneves** [comment]
Reveal serial number done here #528
