### ISSUE TITLE
LOW PRIORITY: New.SyncIDS.com seems to take me straight to login

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#510]
I am sending a marketing campaign out soon which will include the https://new.syncids.com.  However, no matter what I do (clear cache) when I visit new.syncids.com it automatically takes me to the Login screen.

Am I the only one having this problem?

**Comment by ntgn81** [comment]
Yeah, this is because `new.syncids.com` defaults to `App` page, which requires login.

I think we want to default to `App` if user is already logged in.

And default to `Overview` if user is not logged in.

@yneves, let's think about how we can do this.

**Comment by yneves** [comment]
Done here #514

**Comment by JulieJager** [comment]
Hi @ntgn81 Will this fix be rolled out soon?  Waiting to send out marketing email until it's done.  :)

**Comment by ntgn81** [comment]
@JulieJager , totally! I'll make a release tonight.
