### ISSUE TITLE
BUG REPORT:  Delete from All Matters issue

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#512]
When attempting to delete several references using "Delete from All Matters" system gets hung up on a few.  Doesn't delete them (from the UI at least) unless a refresh is done.  Fail status shows in a blink of an eye.  Reference doesn't delete unless a refresh is done.

Also, this might help you locate the problem:  When I try to Delete the last reference in a matter via "Delete from All Matters" the UI does not delete it except when I refresh.

**Comment by yneves** [comment]
@JulieJager I can't reproduce this one in my test db. Which firm/client/matter is it?

**Comment by JulieJager** [comment]
btlawcom.  I recorded a video to show you what happens in syncidscom.  Happens towards the end of Delete from All Matters.  Hope this helps!

https://recordings.join.me/L7ByiwXVTUinFAm4SN0J1g

**Comment by yneves** [comment]
Fixed here https://github.com/syncids/syncids-api/pull/17

**Comment by yneves** [comment]
@JulieJager Very helpful, thanks!
