### ISSUE TITLE
LOW PRIORITY: New UI slowness for large matters

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#513]
I am not sure if this is normal, but the UI does not seem to be creating the tables as quickly as they used to, for large matters.  Have you experienced this?  btlawcom and novelipcom are good examples.

**Comment by JulieJager** [comment]
Hi guys-

It took 5 minutes to build the table for novelip.com database: ENC-ENC602.US.  900+ references.  Is that normal?

**Comment by ntgn81** [comment]
@JulieJager, it definitely doesn't sound normal. We'll investigate.

**Comment by ntgn81** [comment]
Took me around 5-10seconds to load for that matter. Is it taking 5mins for you every time?

**Comment by JulieJager** [comment]
Tried again. About 5 minutes for me via chrome.  See recording here (view in Firefox or Chrome):
https://recordings.join.me/QoBq3R-E80eZ82g3HkU2PA

**Comment by JulieJager** [comment]
Couple minutes for a btlawcom matter as well via chrome.  See recording here: https://recordings.join.me/RSCH8SIk-kGlArdemqDWvw 

I have to tell the browser to "wait" a couple of times as well.

**Comment by ntgn81** [comment]
Hmm the difference must be between our machines. Rendering that many documents does take a toll on the CPU and memory. We'll look into optimizing it.

**Comment by JulieJager** [comment]
Thanks.  FYI: 1st time I noticed it was 8/23.  I do not recall having this issue before that.  I am asking Deb/Maria to test from their machines.  I will let you know.

**Comment by yneves** [comment]
I know what to do to make it better. Will work on it.

**Comment by ntgn81** [comment]
@JulieJager , can you give it a try again, please?

**Comment by JulieJager** [comment]
It's hard to say with the rendering on.  I'm not liking that.  I think I would rather wait for the entire table to build than to get it piece by piece.  Sorry.  I'm sure that was a lot of work.

**Comment by ntgn81** [comment]
Not a problem! It was worth a try :D Having doc sections collapsed by default should help quite a bit.

Thanks for testing!

**Comment by ntgn81** [comment]
@yneves , reverted the changes for now. Let's have collapsible doc sections in before we continue with tackling this. Might not be such a big problem with collapsible sections.

**Comment by ntgn81** [comment]
@JulieJager , can you please double check? The changes are reverted.

**Comment by JulieJager** [comment]
Thanks!  Just thought of a feature we will partially lose with collapsible sections.  Search.  I assume the web browser's search feature will only search what's on the screen, not the collapse sections.  ???

**Comment by JulieJager** [comment]
Took me 1.30 minutes to build a table of 688 references.  I have a new laptop in the box.  I will test from that tomorrow.  Again, could just be my current laptop.
