### ISSUE TITLE
Unique Logins

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#517]
julie@syncids.com@company.com

Law firms and companies are our clients.  Sometimes companies have 2 or more law firms working in their database.  We grant logins to the law firms by way of asking them to enter their real email address followed by the company domain.  Software then grants access to the last domain mentioned.

This ability does not seem to be working currently in the new UI.

**Comment by yneves** [comment]
UI was validating email, should work after #519 gets merged
