### ISSUE TITLE
OLD UI ISSUE - Excel is generating as XML File

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#518]
@ntgn81 See client email below.  I am experience this too.  I thought it was just me.  Generating an excel via old UI is generating excel as an XML File.  

Can you look into this or should I ask Jim?  

From: Amy E. Anders [mailto:AAnders@fitcheven.com] 
Sent: Wednesday, August 31, 2016 2:31 PM
To: Julie SyncIDS <julie@syncids.com>
Subject: Excel 

Hi Julie,

When I open the Excel document to show what has been cited, it does not open and another browser page with a bunch of script comes up.  Can you advise me how to fix?

Thanks,
Amy 

Amy Anders |  Paralegal

**Comment by ntgn81** [comment]
I can look at it in 2 hours.

**Comment by JulieJager** [comment]
Sounds good.  I can generate what she needs in the new UI.

**Comment by ntgn81** [comment]
@JulieJager , do you see the same problem? From what I remember, it's always been returning xml file.

Just need to use excel to open it.

**Comment by JulieJager** [comment]
I see the same problem via old UI. Opens in WordPad instead of Excel. She just upgraded her puter to Window 10.

I recall having this issue when I first started with SyncIDS. I'll play around and see if it's a local setting. Thanks for looking into this.

**Comment by ntgn81** [comment]
Does she have excel installed?

**Comment by ntgn81** [comment]
I think we can change the extension to .xsls. I'll give it a try later
