### ISSUE TITLE
Two-Way sync "add" button not working

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#542]
I was able to sync from the other direction.  Was not able to add a matter to the family via Add button.  

Report from customer:

I have created a matter “Yellowcases-flowloopcases” but I am unable to add Two-way related matters.  For instance, if I add  “C00004925.USU1” I get a red box in the corner saying “failed to add family C00004925.USU1”   The same thing happened when two-way adding C00004927.USU1

**Comment by yneves** [comment]
Fixed.
