### ISSUE TITLE
Maximum number of references has been exceeded

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#552]
This is new to me.  300 limit per form.

![capture](https://cloud.githubusercontent.com/assets/17907226/18621614/9027d648-7deb-11e6-8cad-4a14bc477679.JPG)
[ENC-ENC615_Con_PTO_IDS-Form-A.pdf](https://github.com/syncids/syncids-ui/files/479184/ENC-ENC615_Con_PTO_IDS-Form-A.pdf)

**Comment by ntgn81** [comment]
Oh, it's 300 total for patents and publications. I always thought it was 300 for patents and 300 for publications, making it 600 total.

Might have changed recently. I'll update

**Comment by JulieJager** [comment]
It must be new. I thought what you thought.

**Comment by ntgn81** [comment]
@JulieJager , done. The change is pushed out.

**Comment by ntgn81** [comment]
Can you try the same matter one more time, please?

**Comment by JulieJager** [comment]
Looks good! Thanks!
