### ISSUE TITLE
Batch Input & UI accepted slashes

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#556]
Customer attempted batch upload for the following US Publication Nos. SyncIDS did NOT look up date/inventor and allowed the slashes in the UI.

Report:  pabstpatentcom
I left it the way the system populated in case you wanted to look
SBMRI-SBMRI14-008
I copied from word doc and pasted into batch input, clicked process and then confirm
2010/0173918
2013/0084297

When it did not work the first time I deleted and tried again. Same results

**Comment by yneves** [comment]
Fixed here #559
