### ISSUE TITLE
New @@ logins not working

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#557]
We have situation where several law firms want to log into a shared client's database (e.g., itw.com). Currently, we have users @fyip.com who log into the itw.com database by entering their real emails followed by @itw.com.  The @@ helps us identify the real user in SQL and also allows the immediate SyncIDs invoicing to go directly to them (invoicing ignore 2nd @).  Logging in ignores the first @ and grants access to the 2nd @ (i.e., itw.com).  
EXAMPLE:  fscheel@fyiplaw.com@itw.com (invoices goes to fscheel@fyiplaw.com and access is granted to the itw.com database)

This is not happening with new users via new UI.  
I created (via old UI- not working in new ui) the following user:  
epimentel@mcandrews-ip.com@itw.com 
but it's granting user access to mcandrews-ip.com and not itw.com.

**Comment by ntgn81** [comment]
I'll take a look

**Comment by ntgn81** [comment]
@JulieJager , this is done. Pending code review

**Comment by ntgn81** [comment]
@JulieJager , could you please test and close this? Should be fixed now.

**Comment by JulieJager** [comment]
It's great. Thanks!
