### ISSUE TITLE
Pillsburylaw Accounting

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#566]
Hi @ntgn81 

Pillsburylaw is receiving immediate invoices for client 032296.  We hardcoded something previously that automatically set invoices to monthly regardless of what was picked in the UI.  Could you take a look at that code when you get a chance?  In the meantime, I set this client to monthly on the UI to avoid any more immediate invoicing.

**Comment by ntgn81** [comment]
Is this how we  want to do it? If they can set it on UI, should we just use the UI value instead of hard-coding?

**Comment by JulieJager** [comment]
Well, the problem is not all users know to set a new client to monthly.  This is what happened today.  Can we auto set the UI to monthly for all new pillsurylaw clients?
