### ISSUE TITLE
BUG: Foreign Section

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#568]
Software is auto-striping out any leading 0 from foreign numbers.  Not the 0 we had to differentiate between foreign and US in the backend, but the real leading 0.  Also, the Status Tag doesn't go away.  Seems to be across the board issue.  See recording:

https://recordings.join.me/0GCLPsYaokmHZNDhzeT2ow

**Comment by yneves** [comment]
Done here #581
