### ISSUE TITLE
HIGH PRIORITY: Missing from statdb:  Action "Monthly Bill"

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#571]
I do not see that Monthly Bill is being generated in the statdb. See itw.com statdb for example.  Working fine in early September, but not anymore.

**Comment by JulieJager** [comment]
FYI.  @ntgn81  Some charges were missing from itw monthly invoice and all were missing from Novelip

**Comment by JulieJager** [comment]
We had to audit/manually create several Monthly Bills because this action was missing in some customer's statdb.  We searched action "File IDS" to recreate.

**Comment by ntgn81** [comment]
@JulieJager , can you please give it a test too?

**Comment by JulieJager** [comment]
Seems to be working!! I'll reopen if not.  THANKS, NAM!!!
