### ISSUE TITLE
DeDup Issues

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#572]
I think this came back.  I am not getting an auto-suggest at the client level but the matter level, it seems.

**Comment by JulieJager** [comment]
I take that back.  Now it is showing up.  Seems to be a delay in providing the list.  Maybe a refresh is needed?  I don't know what's going on.

**Comment by JulieJager** [comment]
DeDup auto-suggest is not pulling up-to-date NPLs, not showing more than 4 suggestions (it seems), scroll bar not working (arrow keys work).  See recording:  https://recordings.join.me/9Dyz_sJmCkKqYpteQViOcQ

**Comment by yneves** [comment]
Fixed here #589

**Comment by JulieJager** [comment]
Can we roll this one out soon? :)
