### ISSUE TITLE
Long Client Name issue

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#573]
This client's name is very long.  How can we fix?
![capture](https://cloud.githubusercontent.com/assets/17907226/18798810/e3857bea-8199-11e6-94e8-25e63a06afb6.PNG)

**Comment by ntgn81** [comment]
How does this look?

![image](https://cloud.githubusercontent.com/assets/4622542/18802184/50e9abf0-81b5-11e6-8ef3-b6b12af5a912.png)

**Comment by JulieJager** [comment]
Perfect!
