### ISSUE TITLE
URGENT:  Received 2 reports of not being able to login to SyncIDS

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#578]
I can!  Weird.  Both reports are coming from pillsburylaw.com.

**Comment by ntgn81** [comment]
Weird, did you try with their emails?

**Comment by JulieJager** [comment]
Yes.  It doesn't seem to be an issue on our end (as far as I can tell).  But 2 users at the same firm cannot access SyncIDS.  Weird.  IDK.

**Comment by JulieJager** [comment]
FYI:  They can access the Classic Interface but not the new UI.  ???

**Comment by JulieJager** [comment]
FYI:  It seems we had two issues going on here.  One:  pillsburylaw.com should have an Administrator password generated rather than the random password.  All new users at pillsburylaw.com should have the password:  Gas60.  The welcome to SyncIDS email says something like, "see your administrator for the password".
