### ISSUE TITLE
Make GitHub private if you have not already

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#579]

**Comment by ntgn81** [comment]
@JulieJager, yep. Need to set up the build/release pipeline before we can make it private.

The current pipeline is on free plan and not working with private github.

I'm on it:)

**Comment by JulieJager** [comment]
I did as you instructed below but it is not private - simply google syncids and you get all our GitHub conversations.  Is there a setting I need to change?
========================================
You should receive an invitation to become billing manager on github/syncids group.

After accepting, you can go here to upgrade us to give the ability for creating private repositories:

https://github.com/organizations/syncids/settings/billing

**Comment by ntgn81** [comment]
Nopes! Sorry, I thought I did. Making it private now.
