### ISSUE TITLE
Email Clock has been changed.

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#585]
@ntgn81 Just checking to see if you made any changes to our server clock.  My email said I just sent an email at 4:28 am; however, it is 12:30 pm CT.  Typically our email clock is +/- an hour depending on day light savings time but this is a 4 hour difference.  Typically, when we've seen this in the past, it affected our user's access to PDF.  I think it has something to do with S3.

**Comment by ntgn81** [comment]
Nopes, I didn't. The email that you send using @syncids.com?

**Comment by JulieJager** [comment]
Sent box shows proper time but inbox does not.  Off by 4 hours.  Says its 4:53 now even though its 12:53 ct.  I was in remote desktop yesterday to get a few reports that bombed.  I hope I didn't do anything.  :(  When I first logged in it asked me why my last session abruptly expired and I chose the option "unplugged computer" even though I wasn't in it before. Not sure if its even related but I think it is.

**Comment by ntgn81** [comment]
Hmm, that might have been why. I can log in and take a look later today.

**Comment by ntgn81** [comment]
While we're on this topic. Have you guys looked into google's business account? Can still have email@syncids.com, but will be hosted by google, with gmail.com interface. It's pretty neat

https://apps.google.com/intl/en_us/pricing.html
