### ISSUE TITLE
HIGH PRIORITY:  NPLs w/ and w/o Jim's code

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#586]
@ntgn81 When NonPatentBib descriptions in artdb do not include the Jim coding, a DeDup report via Home 2 will not generate.  

![capture](https://cloud.githubusercontent.com/assets/17907226/18861339/27594f10-844a-11e6-9aa9-7547489953bd.PNG)

I deleted all NPLs from the medtroncisso database that did not have the coding and the DeDup generated great.  I re-added the NPLs via the new UI and the next DeDup did not work.  So, I tried to added them back via home2, but Home2 sucks and it didn't create the NPLs.  Sooo, FYI DeDup reports will not generate when NonPatBib descriptions are inconsistent or without coding (not sure which, really).

**Comment by JulieJager** [comment]
@ntgn81 I know you are preparing to go on vacation, but is there a work-around I could use until this is resolved?  My DeDup reports bomb when they get to NPLs without Jim's coding.

**Comment by ntgn81** [comment]
Yep, let me take a look tonight!

**Comment by ntgn81** [comment]
@JulieJager , can you try again, please?

**Comment by JulieJager** [comment]
It works!  What did you do?  Thank you!

**Comment by ntgn81** [comment]
Perfect! The unencoded text has `'`, and it breaks the SQL query

**Comment by ntgn81** [comment]
I just encoded that character before passing on to sql query
