### ISSUE TITLE
Request to Revert a Client Database

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#587]
@ntgn81 
FirmName:  btlaw.com
Client: 5723
Requestor: Brian Jarman
Request:  Please revert the 5723 database to the evening of September 20 in light of bad syncing by user.  
Thank you!

**Comment by ntgn81** [comment]
Just revert the matters, right?

**Comment by JulieJager** [comment]
I didn't realize we could revert certain DBs.  I think you are asking me if we want to revert the clientdb, artdb, statdb, accountingdb as well for client 5723?

**Comment by ntgn81** [comment]
Oh it's a manual process either way.

If syncing went wrong, it's just the matterdb that got affected.

So we can 

1. delete all matters from matterdb for btlawcom/5723 from current
2. copy all matters from matterdb for btlawcom/5723 from backup

**Comment by JulieJager** [comment]
Sounds right. 👍

**Comment by ntgn81** [comment]
Done. Can you give it a try, please?

**Comment by JulieJager** [comment]
Looks good to me!

**Comment by ntgn81** [comment]
Beautiful! We'll start having much more backups now, they are all on S3.
https://console.aws.amazon.com/s3/home?region=us-east-1&bucket=mysql-syncids-backup&prefix=

**Comment by JulieJager** [comment]
Wow!  That's so cool!!!!  Thank you!
