### ISSUE TITLE
Two-Way Syncing Issue & PDF Uploading Issue

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#59]
Database: lawfirm.com
Client: Acme
Matter: 008

When I linked 008t to the family, the references did not flow.
I could not upload PDFs to NPL67 and NPL68

**Comment by ntgn81** [comment]
@JulieJager , which browser are you on? I was able to create 008t and link it into 008 family.

**Comment by ntgn81** [comment]
@JulieJager , I fixed file upload. I'm not able to reproduce the linking though. Can you?

**Comment by JulieJager** [comment]
Nevermind. Yesterday, I deleted all the uncited references is 008, and removed 008 from the family to prepare for another demo today.  So, when I added 008 to the family today, SyncIDS did the right thing in that it didn't return the DeletedArt when I resynced.  Pretty sure we're ok.  So sorry.

**Comment by ntgn81** [comment]
Awesome, closing this issue.
