### ISSUE TITLE
Default Filer Email/Full Name

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#60]
Lawfirm.com
10000
3

I was trying to enter a new Filer in a Matter Section (to trump the Default Filer in the Client Section) but it instead changed the Default Filer's Full Name and Reg No.

Example, I entered John.Doe@lawfirm.com in Matter section email box; entered John Doe as Full Name, and Reg No. as 11111.  When I tabbed from Full Name to Reg. No. the original email address repopulated, taking on the new Full Name and Reg. No.

**Comment by ntgn81** [comment]
Good catch! It should be fixed in a few minutes.
