### ISSUE TITLE
REPORT: Excel Report will not generate

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#604]
@itwcom
Welding 
Welding | Show All

**Comment by ntgn81** [comment]
@JulieJager , I'm working on moving our services to AWS.

The current free tier provider has memory limit. Excel Report for this case is going over the limit

**Comment by JulieJager** [comment]
Ok.  This explains other encounters as well. Thanks!

**Comment by ntgn81** [comment]
Should be fixed now.

**Comment by JulieJager** [comment]
Gracias!
