### ISSUE TITLE
Matter Section - More Options

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#605]
@yneves The More Options only shows up if a user creates a new matter by replacing an existing matter name (i.e., Clicking "New" does not show the option.  Only replacing a matter name to create a new matter shows the option).

![capture](https://cloud.githubusercontent.com/assets/17907226/19272798/93ff1d3e-8f8f-11e6-8163-74b093f8994f.PNG)

**Comment by yneves** [comment]
Done here #609
