### ISSUE TITLE
New:  To-Do List v. Show All

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#607]
@yneves Can we create a toggle view from To-Do List v. Show All.  Currently, in the Dashboard section when Show All box is unchecked it means the dashboard is showing a To-Do List but that is not clear to our users.  Can we do something that looks similar to view All, Cited, or Uncited in Documents Section?  
To-Do List | Show All  

Default is To-Do List 
 
![capture](https://cloud.githubusercontent.com/assets/17907226/19275777/3c5e34ec-8f9a-11e6-8f0c-48c8378ad5f1.PNG)

**Comment by yneves** [comment]
![image](https://cloud.githubusercontent.com/assets/5215669/19289288/6cf719f2-8fe0-11e6-871a-2f661380eb0b.png)

**Comment by yneves** [comment]
Done here #610
