### ISSUE TITLE
Feature:  View Category

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#614]
In the old UI, users could click "View Category" to see a list of prior art references tagged to a certain category.  We do not yet have this capability in new UI.  See example below:

![capture](https://cloud.githubusercontent.com/assets/17907226/19441225/8f09e79a-944a-11e6-9323-88ecc777670b.PNG)

**Comment by yneves** [comment]
@JulieJager Should it list all references for that category present in the client art db?

**Comment by JulieJager** [comment]
@yneves Yes.  Also, I just noticed...after a user syncs with categories, the tag is not listed in the receiving matter.  So if a user syncs with more than one category, they cannot tell what category the reference(s) came from.

**Comment by yneves** [comment]
Yeah, i'm checking this now, quite tricky.

**Comment by yneves** [comment]
Actually, it looks like the category is removed from all instances of the same document.

**Comment by yneves** [comment]
@JulieJager The problem with losing category is fixed, was just visual, database is intact.

**Comment by JulieJager** [comment]
Thanks!!!!

**Comment by yneves** [comment]
Reopening since its still missing the "view category" feature.

**Comment by yneves** [comment]
![image](https://cloud.githubusercontent.com/assets/5215669/19705277/64b605f4-9aea-11e6-9a05-f7477effa5c4.png)

![image](https://cloud.githubusercontent.com/assets/5215669/19705300/7cc02a44-9aea-11e6-8fac-4adbe688797a.png)

**Comment by yneves** [comment]
Done here #621

**Comment by JulieJager** [comment]
This turned out great!  Thanks @yneves
