### ISSUE TITLE
Revert Request: FirmName: itw.com; Client: Welding

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#615]
@ntgn81 Can you revert the Welding database back to the morning of October 12 CT?  Seems a Data Migration Specialist accidently uploaded the wrong DeDup report and several erroneous references were dedupped out.  

WELCOME BACK! ;)

**Comment by ntgn81** [comment]
Put all matters for itwcom/Welding to what they were on morning Oct 12

**Comment by ntgn81** [comment]
Please let me know if it looks good, @JulieJager

**Comment by JulieJager** [comment]
Dang.  Need to go back further.  Try morning of 10/11.  If NPL 454 is there then we've gone back far enough.  Sorry.

**Comment by ntgn81** [comment]
Which matter are you looking at? The NPLs are not reverted. I only reverted matters

**Comment by JulieJager** [comment]
Looking at SQL.  Maria replaced hundreds of Foreign and NPLs with wrong winners. Can we revert art database too?  Here are some examples.  The report she uploaded was an original.  Original dedups autopick the first reference as the winner.  She needed to move the > to the winning number but she didn't.  She uploaded the original. UGH.

>0003295A1  1/20/2000  WO
 0003781A1  9/5/1979  EP
 0006335A1  2/10/2000  WO
 0012728  6/25/1980  EP
 0014392  3/16/2000  WO
 0023223A1  4/27/2000  WO

>[NPL-0451]  PATENT ABSTRACTS OF JAPAN vol. 2003, no. 12, 5 December 2003 (2003-12-05) & JP 2003 236663 A (DAIHEN CORP), 26 August 2003 (2003-08-26)

 [NPL-0454]  PATENT ABSTRACTS OF JAPAN vol. 2003, no. 7, 3 July 2003 (2003-07-03) & JP 2003, 088957, A, (DAIHEN CORP), 25 March 2003 (2003-03-25)

 [NPL-0453]  PATENT ABSTRACTS OF JAPAN vol. 2003, no. 11, 5 November 2003 (2003-11-05) & JP 2003, 191075, A, (DAIHEN CORP), 8 July 2003 (2003-07-08)

 [NPL-0452]  PATENT ABSTRACTS OF JAPAN vol. 2003, no. 9, 3 September 2003 (2003-09-03) & JP 2003, 154455, A, (DAIHEN CORP), 27 May 2003 (2003-05-27)

**Comment by ntgn81** [comment]
Sure. So you want to revert artdb for itwcom/Welding?

**Comment by JulieJager** [comment]
Yes.  Let's try morning of October 12 and see if that works.

**Comment by ntgn81** [comment]
Done, can you give it a try now?

**Comment by JulieJager** [comment]
BINGO!  I think that did it!  Thank you!!

**Comment by ntgn81** [comment]
Yay
