### ISSUE TITLE
Remote Desktop Pop Up

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#618]
Hi @ntgn81.  I am trying to log into Remote Desktop to solve a migration problem and after logging in with usual credentials, I get the below notice.  Jim said he got it yesterday as well.  When I press ok it logs me out.

Any idea what's going on?  Or, how to get around it?

![capture](https://cloud.githubusercontent.com/assets/17907226/19541337/19196f78-962b-11e6-81c1-c46771978c08.PNG)

**Comment by ntgn81** [comment]
@JulieJager , I'm not quite sure what's happening. Let me restart the box.

**Comment by ntgn81** [comment]
@JulieJager , should be up now
