### ISSUE TITLE
URGENT REPORT:  NPL PDFs mismatched

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#626]
FirmName: parkegal.com
Client: SCTY
Matter: See P67-TEST
Problem:  The PDFs are not matching up with correct reference.  I cannot figure out what happened or how to fix.  Seems like younger NPLs are okay.

**Comment by ntgn81** [comment]
@JulieJager, sounds like problem with s3 links not being updated upon document renaming?

**Comment by JulieJager** [comment]
I don't think so as NPL numbers are not renamed like foreign.

**Comment by JulieJager** [comment]
I take that back.  It might just be.  User may have been DeDuping from the UI.

**Comment by yneves** [comment]
@ntgn81 Is this an API issue? I remember to change something related recently. I might need to fix again.

**Comment by ntgn81** [comment]
I think this is API issue

**Comment by yneves** [comment]
Fixed here https://github.com/syncids/syncids-api/pull/32

**Comment by ntgn81** [comment]
Another guess is that we have dev and production sites. Two different databases, but sharing the same S3 buckets.

We should stop dev site and just use production for now. Until we figure out a better way to isolate the two environments.

Please let me know what you think.


@JulieJager, @yneves

**Comment by JulieJager** [comment]
Agreed.
