### ISSUE TITLE
Information icon needed |  Copy details from Matter

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#629]
@yneves When a user chooses More Options in the New Matter box, please indicate the following in an i icon to the right of "Copy details from matter".  Any format will do (I just copied this from our User Manual).  Thanks!!

Data copied over: 
![capture](https://cloud.githubusercontent.com/assets/17907226/19693293/9a030062-9aa0-11e6-82e9-c3ab8e18d327.PNG)

**Comment by yneves** [comment]
Done here #638
