### ISSUE TITLE
URGENT: Btlaw.com cannot upload PDFs

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#630]
Customer: btlaw.com
Report:  Cannot upload PDFs in its database.  Report lists 47631-233236 as test matter (cannot upload PDFs to foreign matters) but I noticed other clients in the btlaw.com database are affected too.  As are NPLs - cannot upload PDFs there either.  

Works fine in @syncids.com database.

**Comment by JulieJager** [comment]
Just now, I was able to upload one foreign PDF but nothing more.

**Comment by ntgn81** [comment]
Fixed, there was a limit on the size of uploaded file. I increased it to 200MB now.

**Comment by ntgn81** [comment]
@JulieJager , can you please retest this?

**Comment by JulieJager** [comment]
Fixed! Thanks!
