### ISSUE TITLE
SYNCIDS IS DOWN! Deb can't view in any browser

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#632]
and I had a heck of a time during my demo.

**Comment by ntgn81** [comment]
Sorry for that, something's happening to the old server...

**Comment by ntgn81** [comment]
Can someone log on to the old server, and reset IIS, please?

**Comment by ntgn81** [comment]
@JulieJager , it's back on now. My guess is that hitting home2.asp somehow killed the old server, and we still depend on that to generate the transmittal letter.

**Comment by JulieJager** [comment]
Ok.  I see that IDS generator is working again (THANK YOU!) and home2 is up too.  We should try and not depend on old server, yes?

**Comment by ntgn81** [comment]
We still do when we need to generate old ids form and transmittal letter.

I'll look into why it crashed and possibly fix that.

**Comment by JulieJager** [comment]
Ok.  Sounds good.  FYI, Deb, Maria, and I have been in Home2 a lot lately as we have several migrations we are working on.

**Comment by ntgn81** [comment]
Hmm, I wonder if those migration scripts somehow blew up the server

**Comment by ntgn81** [comment]
@JulieJager, for the future. This is something we keep track of. Can you give us a heads up on demos? The earlier the better, we'll try to keep things stable and not hit any pieces that might cause issues for the demo.

**Comment by JulieJager** [comment]
Good point.  May I simply add you and Yuri to my demo WebEx invites?  Or, I can add to GitHub in an Open Issue?

**Comment by ntgn81** [comment]
Yep, webex invites should do, as long as that adds to our calendar.

**Comment by JulieJager** [comment]
Monday AM Jim/I changed the clock to old server.  I was off again 4 hour ahead.  May have been the reason we crashed it.  FYI: my emails are (again) 4 hours again.  NOT a big deal.  I will not change the clock! :)  Just wanted to share my though on this topic.
