### ISSUE TITLE
LOW PRIORITY:  Migration Template not downloading

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#635]
In the Dashboard section, Migration button, the Migration template does not download.  Thanks, as always for looking into this stuff! :)

**Comment by ntgn81** [comment]
Hmm, I don't see that file in src/files anymore. It was there at some point, right, @yneves  ? SyncIDS_Data_Migration_Template.xlsx

**Comment by yneves** [comment]
@ntgn81 This one was still at API server. Moved just now to UI. Here #636
