### ISSUE TITLE
Feature: Sync with categories

### ISSUE THREAD

**Issue by yneves** [syncids/syncids-ui#64]
**Client**
- [x] Add "Categories" column to documents.
- [x] Select which categories the document belongs to.
- [x] Add "Sync With Categories" field at matter form.

**Server**
- [ ] Store categories for each document.
- [ ] Store selected categories for each matter.
- [ ] Automatically sync documents for the selected categories.

**Comment by yneves** [comment]
@ntgn81 Hey, created this issue so we can keep track of progress on categories.

**Comment by yneves** [comment]
All done here @ntgn81?

**Comment by ntgn81** [comment]
Yes Sir
