### ISSUE TITLE
URGENT:  Cannot generate IDSs

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#643]
SyncIDS will not download the IDS forms etc.

Smells like the same thing that happened to us before when Nam was on vacation and Yuri need to reset something.

Is this related to the old server clock again?

**Comment by JulieJager** [comment]
Getting lots of reports.  @yneves Can you put up the notice that the IDS feature is down?  Whatever you put up before?

**Comment by yneves** [comment]
@JulieJager I restarted IIS, same as last time. It seems to be back to normal.

**Comment by JulieJager** [comment]
Thanks!!!!!!!! Are there any reprocussions to the clock, Nam? Can we still upload a and access it?

**Comment by JulieJager** [comment]
...Upload a PDF and access it...

**Comment by ntgn81** [comment]
@JulieJager , I still need to figure out why it's crashing. Did anyone do any batch upload today?

**Comment by ntgn81** [comment]
And pdf upload functionality is still working

**Comment by JulieJager** [comment]
Nope. No batch uploading.

**Comment by JulieJager** [comment]
Actually, let me confirm that 100%.
