### ISSUE TITLE
Cannot view any PDFs via UI

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#644]
I cannot view any PDFs via the UI.  They can download, it seems, but I cannot view.  

I have a demo at 12 pm CT so please do not do anything until after 1 pm. :)

**Comment by ntgn81** [comment]
I can make a quick change to fix it if you'd like.

**Comment by JulieJager** [comment]
ok.  Starting meeting in 5 minutes.

**Comment by ntgn81** [comment]
Nevermind, it requires a bit more work. I'll not make any changes now.

**Comment by JulieJager** [comment]
Demo done.  Feel free to implement at your convenience.

**Comment by yneves** [comment]
@ntgn81 Something weird is going on. First attempt to open PDF in google viewer fails, then if i download the PDF and try google viewer again, it works. Any idea?

**Comment by yneves** [comment]
Actually, simply retrying the google viewer works. No idea why.

**Comment by ntgn81** [comment]
Yeah, it was working for me only if I removed `http://` from the pdf url. but I guess it works now, might have been some temporary changes on google viewer
