### ISSUE TITLE
Delete from ALL matters does not work

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#645]
It says its succesfully removed but its still there when I test/try to add it back in.

**Comment by JulieJager** [comment]
REPORT RECEIEVED:  After entering the description for an NPL reference for the first time for one matter, I want the description to autopopulate when I begin to enter the description in another matter.  I am not getting popups from SynchIDS.

**Comment by yneves** [comment]
@JulieJager Can you explain more? The customer report seems different from your first comment, i'm a bit confused.

**Comment by JulieJager** [comment]
Sorry @yneves .  Delete from ALL matters was not working for me earlier today.  Separately, (but I thought it might be related - maybe not) Auto-Suggest list doesn't always pop-up recently added descriptions.  I have experienced this before but couldn't recreate problem.  Maybe in requires a refresh to see?

**Comment by yneves** [comment]
NPL suggestions are fixed now.

I can't see delete from all matters failing here, maybe it was a specific matter or client?

**Comment by JulieJager** [comment]
Hi @yneves I am not experiencing an issue with Delete from All matters anymore.  Huh. Previously, auto-suggest list would include the recently DeleteAll NPL, but it is not anymore.  Closing.  Thanks!!.
