### ISSUE TITLE
URGENT:  Cannot edit NPL descriptions

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#652]

**Comment by ntgn81** [comment]
Weird, I can, which one are you looking at

**Comment by JulieJager** [comment]
Fitcheven.com reported the issue.  I tested in their database and sure enough it was deleting what I was trying to add.  Same experience in syncids.com database.  Here is a video:

https://recordings.join.me/zU33cYbnZ0KTOQ1qhJMdAg

**Comment by ntgn81** [comment]
@yneves , can it somehow be related to the fix we merged yesterday?

**Comment by yneves** [comment]
probably, it was the only change, i'll fix tonight

**Comment by yneves** [comment]
Fixed here #655

**Comment by JulieJager** [comment]
Shoot.  Still doing something weird.  I thought it was fixed but when I delete text, the deleted text reappears for a second, then deletes.  

https://recordings.join.me/kaNjt5s7k061qso2v9Tuyw

**Comment by yneves** [comment]
Checking..

**Comment by yneves** [comment]
Pushed another fix #657

**Comment by JulieJager** [comment]
Seems to be working! Thanks @yneves !!

**Comment by ntgn81** [comment]
Yay!
