### ISSUE TITLE
LOW PRIORITY:  Add language to invoices

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#653]
Currently, our invoices do not indicate where to send payment to.  Please remove existing language after table and replace with the following:

Please remit payment within 30 days of receipt to the following address:
 
SyncIDS LLC
950 E. State Hwy 114
Suite 160
Southlake, TX 76092

If you have any questions, please contact us at info@syncids.com or 817-722-5776.

Thank you for using SyncIDS.com!

**Comment by ntgn81** [comment]
@JulieJager , added to immediate invoice. Working on monthly invoice, I'll add it there once I'm done.

**Comment by JulieJager** [comment]
Sweet! Looks good.
