### ISSUE TITLE
REPORT:  Filter by family issue

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#654]
@saul.com
When trying to filter to either a To-Do List or Show All SyncIDS is not listing all the matters for the family.

The screenshot below should list 9 matters with Show All on.  Or, 3 matters with To-Do List on.  My guess is the ( ) in the matter name are causing a problem?

![capture](https://cloud.githubusercontent.com/assets/17907226/19942075/76718fc2-a100-11e6-8912-d865392c9f28.PNG)

**Comment by yneves** [comment]
It's done. Now it's showing the entire family.

**Comment by JulieJager** [comment]
Just tested - still experiencing same issue.  See saul.com: 

![capture](https://cloud.githubusercontent.com/assets/17907226/20218123/a1732de0-a7e8-11e6-95f7-fd044a6f2486.PNG)

**Comment by yneves** [comment]
Found the problem and pushed a fix. https://github.com/syncids/syncids-api/pull/37
