### ISSUE TITLE
Daylight Savings Time and Old Server

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#663]
In the past, we would have to reset the old server clock due to time change.  It seems new UI is not phased by time change as newly-entered PDFs can be viewed.  However, Home2 seems to still be affected as I cannot view any newly-entered PDFs (not saving to S3).

We still need Home2 to upload NPL PDFs in batch during migrations.  Thanks for taking a look when you can.

**Comment by ntgn81** [comment]
@JulieJager , I'll take a look later today!

**Comment by JulieJager** [comment]
@ntgn81 Looks like this might just be a data problem with @syncids.com database as it works with other databases (e.g., goedken.com, jager.com).
