### ISSUE TITLE
Default Filer issues in UI

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#665]
@yneves When creating or editing a Default Filer,  the cells are acting funny.  Sometimes you have to enter data twice, sometimes it won't let you delete the first few letters, and after deleting an entire piece of data, the UI shows it again briefly before actually deleting it.  Thanks for looking into this.  I will follow up with a recording soon.

**Comment by JulieJager** [comment]
https://recordings.join.me/TTX5BEe3oEWASHxcJqiPfw

**Comment by yneves** [comment]
Fixed here #666
