### ISSUE TITLE
Request to call customer's IT team - SyncIDS not useable for unknown reason

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#667]
New customer: GlobalPatentGroup.com.

When they visit www.syncids.com they do not see:

![capture](https://cloud.githubusercontent.com/assets/17907226/20186564/236ac03c-a736-11e6-8170-7a6c57763206.PNG)

Web page is scrambled looking via Chrome and IE.  They confirmed their Windows version is up to date.  Could one of you call The Miller Group (their IT), say you are calling about an IT issue Global Patent Group is having with SyncIDS.  Ask for Dave Grass, if available but any person should be fine.  The Miller Group # 314-822-8090.

**Comment by JulieJager** [comment]
This is what they see:

![capture2](https://cloud.githubusercontent.com/assets/17907226/20186884/68d767fa-a737-11e6-951c-7bfd7b30801e.png)

**Comment by ntgn81** [comment]
@JulieJager, I'm stuck in meetings. Can you ask them to try opening this link from that machine?

https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.6/darkly/bootstrap.min.css

That's where the styling for the site is coming from.

**Comment by JulieJager** [comment]
Yes.  What is suppose to happen if they can/can't?

**Comment by ntgn81** [comment]
If they can, we'll need further investigation.

If they can't, that must be some kind of firewall on their side - we'll need to move these files over to our server.

**Comment by JulieJager** [comment]
This is what she sees when accessing that url (I see the same thing):

![capture2](https://cloud.githubusercontent.com/assets/17907226/20193236/cb462b36-a752-11e6-9365-7ba280ee5390.png)

**Comment by ntgn81** [comment]
Can you ask her to do this, please?

- Use chrome
- Click on menu on top right -> More Tools -> Developer Tools
- In the Developer tool panel that opens up, click on Network -> Filter Icon -> CSS sub tab
- Open syncids.com

I would like to see what the network tab in developer's tool shows once our app loads.

![syncids](https://cloud.githubusercontent.com/assets/4622542/20193571/88f4f9e2-a75c-11e6-8c6d-42c10611a3d2.gif)

**Comment by JulieJager** [comment]
So she did what you asked and now it works for her!  Shrug - haha.  THANK YOU!!

**Comment by ntgn81** [comment]
Weird lol
