### ISSUE TITLE
URGENT: Jim & I cannot receive email. Last received was last night

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#668]
Related to what you did to fix the IDS generator? @ntgn81

**Comment by ntgn81** [comment]
Hmm must be, I'm restarting the email server right now.

**Comment by ntgn81** [comment]
@JulieJager , I just restarted it. Can you try sending an email to yourself, please?

**Comment by JulieJager** [comment]
Receiving now.  Thanks!!

**Comment by ntgn81** [comment]
@JulieJager , great!

Here's the thing I was talking about yesterday: 

https://gsuite.google.com

**Comment by JulieJager** [comment]
Great.  Thanks.  I'll look into it.
