### ISSUE TITLE
Confirm/Prompt modals flow

### ISSUE THREAD

**Issue by ntgn81** [syncids/syncids-ui#75]
Since we are replacing the browser's default (blocking) implementation with custom (non blocking), I wonder if it's cleaner to make them functions - similar to defaults - that returns a promise.

The promise can be resolved (with new message in case of prompt), or rejected. This way the caller component does not need to maintain a state.

That way it's easier to replace default implementations, something like:

```js
// old 
var msg = prompt('enter something');
console.log(msg);

// new
customPrompt('enter something').then(msg => console.log(msg))
```

@yneves

**Comment by yneves** [comment]
I don't agree here. I think its best to render stuff in the same tree, keeping components atomic, even if that means managing state. It's much more react-like.

**Comment by ntgn81** [comment]
Ok, that makes sense.
